services:
  ljvis_xtee_mock:
    image: turnerrainer/ruuter:0.10.1-rc@sha256:98ed90914d30d2e131cc194076c7047aba93727461c05da9bddbcc783880cb37
    container_name: ljvis_xtee_mock
    volumes:
      - ../../DSL/Ruuter/xtee-mock:/app/DSL/xtee-mock:ro
      - ./ruuter.mock.yaml:/app/ruuter.yaml:ro
      - /app/DSL/samples
      - /app/DSL/guarded-demo
    ports:
      - "40386:8080"
