server {
    listen 3001;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /tim/ {
        proxy_pass http://tim:8085/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
        proxy_cookie_flags ~ SameSite=Lax;
    }

    location /api/ {
        proxy_pass http://ruuter:8086/ljvis/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Cookie $http_cookie;
        proxy_pass_header Set-Cookie;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
