-- liquibase formatted sql
-- changeset ljvis:20260605100000 ignore:true

-- 1. audit_event
CREATE TABLE ljvis2.audit_event (
                             id                          BIGSERIAL       NOT NULL,
                             event_type                  VARCHAR(100)    NOT NULL,
                             event_category              VARCHAR(50)     NOT NULL,
                             actor_name                  VARCHAR(400),
                             actor_personal_code         VARCHAR(50),
                             description                 VARCHAR(500)    NOT NULL,
                             log_content                 JSONB           NOT NULL DEFAULT '{}',
                             created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
                             created_by                  VARCHAR(100)    NOT NULL,
                             CONSTRAINT pk_audit_event PRIMARY KEY (id)
);

COMMENT ON TABLE  ljvis2.audit_event IS 'INSERT-only, append-only database audit log. One immutable row per logged business event across the system (who did what, about whom, when, with what scope). Fully denormalised — no foreign keys to any other table. Written via the reusable /api/v1/internal/audit/record endpoint (T1). Read by the audit-log viewing page (T2). Aged rows are later moved to a separate audit database by EPIC 17 (MFN: audit DB independent of the working DB).';
COMMENT ON COLUMN ljvis2.audit_event.id IS 'Primary key';
COMMENT ON COLUMN ljvis2.audit_event.event_type IS 'Event-type code in resource.action[.qualifier] form (lowercase dotted), e.g. user.create, auth.login.success. Defined in application code, not in a catalogue table — consistent with the status-code pattern (Rule #12). Canonical codes are listed in §6 of this document';
COMMENT ON COLUMN ljvis2.audit_event.event_category IS 'Event category for grouping/filtering: authentication, user_management, classifier_management, access_control, system_process. Written alongside event_type at emission time; values defined in application code';
COMMENT ON COLUMN ljvis2.audit_event.actor_name IS 'Display name of the actor (e.g. "Kaiko Kell") captured at write time. Denormalised text — no FK to user_account. NULL for citizen authentication events where the actor is identified only by actor_personal_code';
COMMENT ON COLUMN ljvis2.audit_event.actor_personal_code IS 'Personal code (isikukood) of the actor, captured at write time. Stored in cleartext in the database audit log (permitted for the LJVIS DB); hashing is required only in application logs. Present for both internal users and external citizens when the code is known';
COMMENT ON COLUMN ljvis2.audit_event.description IS 'Short human-readable summary of the audit event (e.g. "Kasutaja Jaan Tamm loodud", "Kasutajagrupp Inspektorid muudetud"). Gives an at-a-glance understanding of the log record; log_content holds the full structured detail. Generated by the emitting code at write time';
COMMENT ON COLUMN ljvis2.audit_event.log_content IS 'Flexible JSONB field for event-specific structured data. Contents depend on event_type. Common keys include: targetPersonalCode (personal code of the user the action was about), targetName (display name of the target user), organisationId (organisation scope/context), scope (allOrganisations | ownOrganisation), searchTerm (full search text as entered by the user, stored in cleartext in the DB audit log), displayedPersonalCodes (personal codes of persons whose data was displayed), changedFields (array of field names only, never values), addedGroups, removedGroups, previousOrganisationId, newOrganisationId, fromStatus, toStatus, targetEntityType, targetEntityId';
COMMENT ON COLUMN ljvis2.audit_event.created_at IS 'Event timestamp (UTC). The audit log is append-only so this also serves as the business event time; rendered as dd.MM.yyyy HH:mm in the UI';
COMMENT ON COLUMN ljvis2.audit_event.created_by IS 'Identifier of the user or process that wrote the record (denormalised text, e.g. "Kaiko Kell" or "SYSTEM"). Consistent with the VARCHAR(100) created_by pattern used across EPIC 02/04 tables. Equals the acting internal user for user-initiated events; the system service account name (provisioned by T3) for platform/anonymous/system-process events';

CREATE INDEX idx_ae_created_at ON ljvis2.audit_event (created_at DESC);
CREATE INDEX idx_ae_event_type ON ljvis2.audit_event (event_type);
CREATE INDEX idx_ae_event_category ON ljvis2.audit_event (event_category);
CREATE INDEX idx_ae_actor_name ON ljvis2.audit_event (actor_name);
CREATE INDEX idx_ae_actor_personal_code ON ljvis2.audit_event (actor_personal_code);
CREATE INDEX idx_ae_log_content_gin ON ljvis2.audit_event USING GIN (log_content);