-- liquibase formatted sql
-- changeset ljvis:20260605100000 ignore:true
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS audit;

-- 1. audit_event
CREATE TABLE audit.audit_event (
    id                          BIGSERIAL       NOT NULL,
    event_type                  VARCHAR(100)    NOT NULL,
    event_category              VARCHAR(50)     NOT NULL,
    actor_name                  VARCHAR(400),
    actor_personal_code_hash    BYTEA,
    description                 VARCHAR(500)    NOT NULL,
    log_content                 JSONB           NOT NULL DEFAULT '{}',
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by                  VARCHAR(100)    NOT NULL,
    prev_row_hash               BYTEA           NOT NULL DEFAULT '\x00',
    row_hash                    BYTEA           NOT NULL DEFAULT '\x00',
    CONSTRAINT pk_audit_event PRIMARY KEY (id)
);

COMMENT ON TABLE  audit.audit_event IS 'INSERT-only, append-only database audit log. One immutable row per logged business event across the system (who did what, about whom, when, with what scope). Fully denormalised — no foreign keys to any other table. Tamper-evident: every row carries a row_hash chained to the previous row via prev_row_hash (see audit.chain_tip). Aged rows are later moved to a separate audit database by EPIC 17.';
COMMENT ON COLUMN audit.audit_event.id IS 'Primary key (BIGSERIAL). Also used as the canonical row order in the hash chain.';
COMMENT ON COLUMN audit.audit_event.event_type IS 'Event-type code in resource.action[.qualifier] form (lowercase dotted), e.g. user.create, auth.login.success. Defined in application code, not in a catalogue table. Canonical codes are listed in audit-logging.md §6.';
COMMENT ON COLUMN audit.audit_event.event_category IS 'Event category for grouping/filtering: authentication, user_management, classifier_management, access_control, system_process. Written alongside event_type at emission time; values defined in application code.';
COMMENT ON COLUMN audit.audit_event.actor_name IS 'Display name of the actor (e.g. "Kaiko Kell") captured at write time. Denormalised text — no FK to user_account. NULL for system-process events.';
COMMENT ON COLUMN audit.audit_event.actor_personal_code_hash IS 'SHA-256 hash of the actor personal code salted with app.audit_salt DB parameter: digest(personal_code || current_setting(''app.audit_salt'', true), ''sha256''). Computed by RESQL insert_audit_event at write time. NULL if personal code is unknown. Cleartext personal codes are never stored.';
COMMENT ON COLUMN audit.audit_event.description IS 'Short human-readable summary of the event (e.g. "Kasutaja Jaan Tamm loodud"). Generated by the emitting DSL at write time. log_content holds the full structured detail.';
COMMENT ON COLUMN audit.audit_event.log_content IS 'Flexible JSONB field for event-specific structured data. Contents depend on event_type. Common keys: targetPersonalCode, targetName, organisationId, scope, searchTerm, displayedPersonalCodes, changedFields, addedGroups, removedGroups.';
COMMENT ON COLUMN audit.audit_event.created_at IS 'Event timestamp (UTC). The audit log is append-only so this also serves as the business event time; rendered as dd.MM.yyyy HH:mm in the UI.';
COMMENT ON COLUMN audit.audit_event.created_by IS 'Identifier of the user or process that wrote the record (denormalised text, e.g. "Kaiko Kell" or "SYSTEM").';
COMMENT ON COLUMN audit.audit_event.prev_row_hash IS 'row_hash of the immediately preceding row in insertion order (id-1). First row uses the sentinel value ''\x00''. Written by the audit.chain() BEFORE INSERT trigger.';
COMMENT ON COLUMN audit.audit_event.row_hash IS 'sha256(id::text || event_type || created_at::text || coalesce(actor_personal_code_hash_hex,'''') || log_content::text || encode(prev_row_hash,''hex'')). Written by the audit.chain() BEFORE INSERT trigger. Any tamper breaks the chain at the following row.';

-- 2. chain_tip — single-row table holding the latest row_hash; SELECT FOR UPDATE serialises concurrent INSERTs
CREATE TABLE audit.chain_tip (
    id       SMALLINT PRIMARY KEY DEFAULT 1,
    row_hash BYTEA    NOT NULL    DEFAULT '\x00',
    CONSTRAINT single_row CHECK (id = 1)
);
INSERT INTO audit.chain_tip DEFAULT VALUES;

COMMENT ON TABLE  audit.chain_tip IS 'Single-row sentinel table for the audit hash chain. Holds the row_hash of the most recently inserted audit_event row. The audit.chain() trigger locks this row with SELECT FOR UPDATE to serialise concurrent inserts and prevent chain forks.';
COMMENT ON COLUMN audit.chain_tip.row_hash IS 'row_hash of the last inserted audit.audit_event row. Initialised to ''\x00'' (sentinel for the empty chain).';

-- 3. Hash-chain trigger function
CREATE FUNCTION audit.chain() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    prev bytea;
BEGIN
    SELECT row_hash INTO prev
      FROM audit.chain_tip
     WHERE id = 1
       FOR UPDATE;

    NEW.prev_row_hash := prev;
    NEW.row_hash := digest(
        NEW.id::text || NEW.event_type ||
        NEW.created_at::text ||
        coalesce(encode(NEW.actor_personal_code_hash, 'hex'), '') ||
        NEW.log_content::text ||
        encode(prev, 'hex'),
        'sha256');

    UPDATE audit.chain_tip
       SET row_hash = NEW.row_hash
     WHERE id = 1;

    RETURN NEW;
END $$;

CREATE TRIGGER audit_event_chain
    BEFORE INSERT ON audit.audit_event
    FOR EACH ROW EXECUTE FUNCTION audit.chain();

-- 4. Indexes
CREATE INDEX idx_ae_created_at              ON audit.audit_event (created_at DESC);
CREATE INDEX idx_ae_event_type              ON audit.audit_event (event_type);
CREATE INDEX idx_ae_event_category          ON audit.audit_event (event_category);
CREATE INDEX idx_ae_actor_name              ON audit.audit_event (actor_name);
CREATE INDEX idx_ae_actor_personal_code_hash ON audit.audit_event (actor_personal_code_hash);
CREATE INDEX idx_ae_log_content_gin         ON audit.audit_event USING GIN (log_content);

-- 5. app.audit_salt database parameter (value injected by Liquibase from AUDIT_SALT env var)
ALTER DATABASE ljvis_db SET app.audit_salt = '${AUDIT_SALT}';
