-- liquibase formatted sql
-- changeset ljvis:20261125100000 ignore:true
--
-- RSI_FAILED_REASON — liiklevate tarbesõidukite tehnokontrolli teate (ERRU RSI)
-- kontrollitud punktide ja mitteläbimise põhjuste klassifikaator.
--
-- Allikas: Euroopa Parlamendi ja nõukogu direktiiv 2014/47/EL (ELT L 127,
-- 29.4.2014) eestikeelne tekst — II lisa (punktid 0–9) ja III lisa (10 sõiduki
-- sobivus, 20 kinnitusmeetodid, 30 veos täielikult kinnitamata). Lehtede
-- koodid on täpselt ERRU rsiFailedReason väärtused (contracts/erru/3.5/
-- RoadSideInspection_Types.xsd, 476 tk) ja saadetakse teates muutmata kujul.
--
-- Struktuur (parent_key):
--   * 1. tase '0'..'10', '20' = ERRU rsiItemType (plokk "Kontrollitud punkt").
--   * 'G:<nr>' = pealkirja-/aspektirühm (nt 'G:1.1', 'G:1.1.3'); ei saadeta.
--     Tähiseta põhjusel (nt 1.1.4) on oma aspektirühm 'G:1.1.4', et aspekti
--     nimi ja põhjuse tekst oleksid eraldi.
--   * Leht (ilma alamkirjeteta) = valitav mitteläbimise põhjus; description =
--     lubatud hinnangud komaeraldatult (VO = väheoluline, OV = oluline,
--     EOV = ohtlik), sama muster nagu TECHNICAL_CHECK-il. '30' asub punkti 20 all.
--
-- Erinevused lähtetekstist:
--   * 9.9 — direktiivis tähisega a), ERRU koodis tähiseta ('9.9').
--   * 4.1.2.b — direktiivi tabelis hinnang märkimata; VO vana süsteemi vormi ja
--     direktiivi 2014/45/EL I lisa järgi.
--   * 8.2.1.2.b — tekst üle name VARCHAR(500) piiri; teise alapunkti korduv
--     lõpuosa lühendatud ("vastavalt samale kuupäevale", "sellise süsteemi abil").
--   * Joonealused viited on eemaldatud.
--
-- Riiklik TECHNICAL_CHECK (tehnoseisundi kontrollkaart) jääb muutmata — see
-- järgib riiklikku määrust (vt 20261120100000). RSI teade kasutab ainult seda
-- klassifikaatorit.
--
-- Lisaks kustutatakse saatmata RSI mustandid (kõik snapshotid 'initiated'),
-- sest nende checked_items on vanas TECHNICAL_CHECK-kujus (kasutaja otsus
-- 2026-09-23). Saadetud, vastatud ja vigased teated jäävad alles ning neid
-- kuvatakse vana kuju toega.
--
-- Idempotentne: klassifikaator luuakse ainult siis, kui seda veel pole.

DO $$
DECLARE
    v_key BIGINT;
BEGIN
    IF EXISTS (SELECT 1 FROM classifier.classifier WHERE code = 'RSI_FAILED_REASON') THEN
        RAISE NOTICE 'RSI_FAILED_REASON already exists, skipping';
    ELSE
        INSERT INTO classifier.classifier (classifier_key, code, name, description, created_by)
        VALUES (nextval('classifier.seq_classifier_key'), 'RSI_FAILED_REASON',
                'RSI kontrollitud punktid ja mitteläbimise põhjused',
                'Direktiivi 2014/47/EL II ja III lisa. 1. tase = ERRU rsiItemType, lehed = ERRU rsiFailedReason; lehe kirjeldus = lubatud hinnangud (VO,OV,EOV).',
                'system')
        RETURNING classifier_key INTO v_key;

        -- Keys are allocated first, so parent_key can be resolved regardless of row order.
        CREATE TEMP TABLE tmp_rsi_failed_reason ON COMMIT DROP AS
        SELECT t.code, t.parent_code, t.name, t.severities,
               nextval('classifier.seq_classifier_value_key') AS value_key
        FROM (VALUES
        ('0', '', 'Sõiduki identifitseerimine', ''),
        ('G:0.1', '0', 'Registreerimismärgid (kui need on nõuete kohaselt vajalikud)', ''),
        ('0.1.a', 'G:0.1', 'Registreerimismärk puudub (registreerimismärgid puuduvad) või on kinnitatud nii ebakindlalt, et see võib (need võivad) ära kukkuda.', 'OV'),
        ('0.1.b', 'G:0.1', 'Kiri puudub või on loetamatu.', 'OV'),
        ('0.1.c', 'G:0.1', 'Ei vasta sõiduki dokumentidele või registrikirjetele.', 'OV'),
        ('G:0.2', '0', 'Valmistajatehase tähis / tehasetähis / seerianumber', ''),
        ('0.2.a', 'G:0.2', 'Puudub või seda ei ole võimalik leida.', 'OV'),
        ('0.2.b', 'G:0.2', 'Mittetäielik, loetamatu, ilmselgelt võltsitud, ei vasta sõiduki dokumentidele.', 'OV'),
        ('0.2.c', 'G:0.2', 'Sõiduki dokumendid on loetamatud või sisaldavad tehnilisi vigu.', 'VO'),
        ('1', '', 'Pidurisüsteem', ''),
        ('G:1.1', '1', 'Mehaaniline seisund ja toimimine', ''),
        ('G:1.1.1', 'G:1.1', 'Sõidupiduri pedaali / käsipiduri hoova šarniir', ''),
        ('1.1.1.a', 'G:1.1.1', 'Šarniir on liiga tihke.', 'OV'),
        ('1.1.1.b', 'G:1.1.1', 'Ülemäärane kulumine või lõtk.', 'OV'),
        ('G:1.1.2', 'G:1.1', 'Pedaali / käsipiduri hoova seisund ja pidurijuhtimisseadme käigutagavara', ''),
        ('1.1.2.a', 'G:1.1.2', 'Liigne või ebapiisav käigutagavara. Pidurit ei saa täielikult rakendada või on see blokeeritud.', 'OV,EOV'),
        ('1.1.2.b', 'G:1.1.2', 'Pidurdusseadis ei vabane korralikult. Toimimine on häiritud.', 'VO,OV'),
        ('1.1.2.c', 'G:1.1.2', 'Piduripedaali libisemisvastane osa puudub, on lahtine või siledaks kulunud.', 'OV'),
        ('G:1.1.3', 'G:1.1', 'Vaakumpump või kompressor ja mahutid', ''),
        ('1.1.3.a', 'G:1.1.3', 'Ebapiisav õhurõhk / vaakum, et võimaldada vähemalt nelja piduri rakendamist pärast hoiatusseadise töölehakkamist (või kui mõõtur näitab ohtu); vähemalt kahe piduri rakendamist pärast hoiatusseadise töölehakkamist (või kui mõõtur näitab ohtu).', 'OV,EOV'),
        ('1.1.3.b', 'G:1.1.3', 'Ohutuks tööks vajaliku õhurõhu/vaakumi tekkeks kuluv aeg on nõudeid arvestades liiga pikk.', 'OV'),
        ('1.1.3.c', 'G:1.1.3', 'Mitmemähiseline kaitseklapp või rõhualandusventiil ei tööta.', 'OV'),
        ('1.1.3.d', 'G:1.1.3', 'Märkimisväärset rõhulangust põhjustav õhuleke või kuuldavad õhulekked.', 'OV'),
        ('1.1.3.e', 'G:1.1.3', 'Pidurisüsteemi toimimist mõjutada võiv väline kahjustus. Varupiduri tõhusus ei ole piisav.', 'OV,EOV'),
        ('G:1.1.4', 'G:1.1', 'Alarõhu hoiatusmärgutuli või mõõtur', ''),
        ('1.1.4', 'G:1.1.4', 'Defektne mõõtur või märgutuli või mõõturi või märgutule rike. Alarõhku ei ole võimalik kindlaks teha.', 'VO,OV'),
        ('G:1.1.5', 'G:1.1', 'Seisupidurikraan', ''),
        ('1.1.5.a', 'G:1.1.5', 'Käepide on pragunenud, kahjustunud või liigselt kulunud.', 'OV'),
        ('1.1.5.b', 'G:1.1.5', 'Ebakindel klapivõll või klapp.', 'OV'),
        ('1.1.5.c', 'G:1.1.5', 'Ühendused on lahti või süsteem lekib.', 'OV'),
        ('1.1.5.d', 'G:1.1.5', 'Toimib mitterahuldavalt.', 'OV'),
        ('G:1.1.6', 'G:1.1', 'Seisupiduri tööseade, pidurikang, piduri lukustus, elektrooniline seisupidur', ''),
        ('1.1.6.a', 'G:1.1.6', 'Piduri lukustus ei tööta nõuetekohaselt.', 'OV'),
        ('1.1.6.b', 'G:1.1.6', 'Kangiliigend või lukustusmehhanism on kulunud. Ülemäärane kulumine.', 'VO,OV'),
        ('1.1.6.c', 'G:1.1.6', 'Kangi liigne liikumine, mis viitab ebaõigele reguleerimisele.', 'OV'),
        ('1.1.6.d', 'G:1.1.6', 'Tööseade puudub, see on kahjustunud või ei tööta.', 'OV'),
        ('1.1.6.e', 'G:1.1.6', 'Mitterahuldav toimimine, hoiatusmärgutuli näitab riket.', 'OV'),
        ('G:1.1.7', 'G:1.1', 'Piduriklapid/ventiilid (jalgpidurikraanid, rõhualandajad, regulaatorid)', ''),
        ('1.1.7.a', 'G:1.1.7', 'Klapp/ventiil on kahjustunud või õhku lekib liigselt. Toimimine on häiritud.', 'OV,EOV'),
        ('1.1.7.b', 'G:1.1.7', 'Kompressorist tuleb liigselt õli.', 'VO'),
        ('1.1.7.c', 'G:1.1.7', 'Klapp/ventiil on ebakindel või valesti paigaldatud.', 'OV'),
        ('1.1.7.d', 'G:1.1.7', 'Hüdraulikavedeliku leke. Toimimine on häiritud.', 'OV,EOV'),
        ('G:1.1.8', 'G:1.1', 'Haagisepidurite ühendused (elektri- ja pneumoühendused)', ''),
        ('1.1.8.a', 'G:1.1.8', 'Kraan või isetihenev ventiil on defektne. Toimimine on häiritud.', 'VO,OV'),
        ('1.1.8.b', 'G:1.1.8', 'Kraan või klapp on ebakindel või valesti paigaldatud. Toimimine on häiritud.', 'VO,OV'),
        ('1.1.8.c', 'G:1.1.8', 'Ülemäärased lekked. Toimimine on häiritud.', 'OV,EOV'),
        ('1.1.8.d', 'G:1.1.8', 'Ei tööta õigesti. Piduri toimimine on häiritud.', 'OV,EOV'),
        ('G:1.1.9', 'G:1.1', 'Energiavaru survepaak', ''),
        ('1.1.9.a', 'G:1.1.9', 'Paak on kergelt kahjustunud või kergelt korrodeerunud. Paak on tugevalt kahjustunud, korrodeerunud või lekib.', 'VO,OV'),
        ('1.1.9.b', 'G:1.1.9', 'Äravooluseade ei tööta.', 'OV'),
        ('1.1.9.c', 'G:1.1.9', 'Paak on ebakindel või valesti paigaldatud.', 'OV'),
        ('G:1.1.10', 'G:1.1', 'Pidurivõimendid, peasilinder (hüdraulilistel süsteemidel)', ''),
        ('1.1.10.a', 'G:1.1.10', 'Võimendi on defektne või ebatõhus. Kui ei tööta.', 'OV,EOV'),
        ('1.1.10.b', 'G:1.1.10', 'Peasilinder on defektne, kuid pidur siiski toimib. Peasilinder on defektne või lekib.', 'OV,EOV'),
        ('1.1.10.c', 'G:1.1.10', 'Peasilinder on ebakindel, kuid pidur siiski toimib. Peasilinder on ebakindel.', 'OV,EOV'),
        ('1.1.10.d', 'G:1.1.10', 'Pidurivedelikku ei ole piisavas koguses, tase allpool miinimummärki. Pidurivedeliku tase on oluliselt allpool miinimummärki. Pidurivedelik ei ole nähtav.', 'VO,OV,EOV'),
        ('1.1.10.e', 'G:1.1.10', 'Puudub peasilindri paagi kork.', 'VO'),
        ('1.1.10.f', 'G:1.1.10', 'Pidurivedeliku hoiatuslamp põleb või on defektne.', 'VO'),
        ('1.1.10.g', 'G:1.1.10', 'Pidurivedeliku taseme hoiatussüsteem ei tööta korralikult.', 'VO'),
        ('G:1.1.11', 'G:1.1', 'Jäigad piduritorud', ''),
        ('1.1.11.a', 'G:1.1.11', 'Ilmne purunemise või pragunemise oht.', 'EOV'),
        ('1.1.11.b', 'G:1.1.11', 'Torud või ühenduskohad lekivad (õhkpidurisüsteemid). Torud või ühenduskohad lekivad (hüdraulilised pidurisüsteemid).', 'OV,EOV'),
        ('1.1.11.c', 'G:1.1.11', 'Torud on kahjustunud või ülemäära korrodeerunud. Mõjutab pidurite toimimist blokeerumise või ilmse lekkeohu tõttu.', 'OV,EOV'),
        ('1.1.11.d', 'G:1.1.11', 'Torud on paigaldatud valesse kohta. Kahjustusoht.', 'VO,OV'),
        ('G:1.1.12', 'G:1.1', 'Elastsed pidurivoolikud', ''),
        ('1.1.12.a', 'G:1.1.12', 'Ilmne purunemise või pragunemise oht.', 'EOV'),
        ('1.1.12.b', 'G:1.1.12', 'Voolikud on kahjustunud, hõõrdunud, väändunud või liiga lühikesed. Voolikud on kahjustunud või hõõrdunud.', 'VO,OV'),
        ('1.1.12.c', 'G:1.1.12', 'Voolikud või ühenduskohad lekivad (õhkpidurisüsteemid). Voolikud või ühenduskohad lekivad (hüdraulilised pidurisüsteemid).', 'OV,EOV'),
        ('1.1.12.d', 'G:1.1.12', 'Voolikud paisuvad rõhu all. Koorti seisund on halvenenud.', 'OV,EOV'),
        ('1.1.12.e', 'G:1.1.12', 'Voolikud on poorsed.', 'OV'),
        ('G:1.1.13', 'G:1.1', 'Piduri hõõrdkatted ja -klotsid', ''),
        ('1.1.13.a', 'G:1.1.13', 'Katted on ülemääraselt kulunud (kulumine on jõudnud miinimummärgistuseni). Katted on ülemääraselt kulunud (miinimummärgistus ei ole nähtav).', 'OV,EOV'),
        ('1.1.13.b', 'G:1.1.13', 'Katted on määrdunud (õli, määre jne). Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.13.c', 'G:1.1.13', 'Kate või klots puudub või on valesti paigaldatud.', 'EOV'),
        ('G:1.1.14', 'G:1.1', 'Piduritrumlid, pidurikettad', ''),
        ('1.1.14.a', 'G:1.1.14', 'Trumlid või kettad on kulunud. Trumlid või kettad on ülemääraselt kriimustatud või pragunenud, ebakindlad või mõranenud.', 'OV,EOV'),
        ('1.1.14.b', 'G:1.1.14', 'Trumlid või kettad on määrdunud (õli, määre jne). Pidurdustõhusus on oluliselt halvenenud.', 'OV,EOV'),
        ('1.1.14.c', 'G:1.1.14', 'Trumlid või kettad puuduvad.', 'EOV'),
        ('1.1.14.d', 'G:1.1.14', 'Alusplaat on ebakindel.', 'OV'),
        ('G:1.1.15', 'G:1.1', 'Piduritrossid, -vardad, -hoovastik', ''),
        ('1.1.15.a', 'G:1.1.15', 'Tross on kahjustunud või sõlmes. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.15.b', 'G:1.1.15', 'Komponent on ülemääraselt kulunud või korrodeerunud. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.15.c', 'G:1.1.15', 'Tross, varras või liitmik on ebakindel.', 'OV'),
        ('1.1.15.d', 'G:1.1.15', 'Trossijuhik on defektne.', 'OV'),
        ('1.1.15.e', 'G:1.1.15', 'Pidurisüsteemi vaba liikumine on piiratud.', 'OV'),
        ('1.1.15.f', 'G:1.1.15', 'Hoovad/liitmikud ei liigu õigesti, viidates valele reguleerimisele või liigsele kulumisele.', 'OV'),
        ('G:1.1.16', 'G:1.1', 'Piduri tööseadmed (sh vedruakud või hüdraulilised silindrid)', ''),
        ('1.1.16.a', 'G:1.1.16', 'Tööseade on mõranenud või kahjustunud. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.16.b', 'G:1.1.16', 'Tööseade lekib. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.16.c', 'G:1.1.16', 'Tööseade on ebakindel või valesti paigaldatud. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.16.d', 'G:1.1.16', 'Tööseade on ülemäära korrodeerunud. Võib mõraneda.', 'OV,EOV'),
        ('1.1.16.e', 'G:1.1.16', 'Survekolvi või -membraani ebapiisav või ülemäärane vabakäik. Pidurdustõhusus on halvenenud (liikumisvaru puudub).', 'OV,EOV'),
        ('1.1.16.f', 'G:1.1.16', 'Tolmukaitse on kahjustunud. Tolmukaitse puudub või on ülemäära kahjustunud.', 'VO,OV'),
        ('G:1.1.17', 'G:1.1', 'Koormuse regulaator', ''),
        ('1.1.17.a', 'G:1.1.17', 'Ühendused on defektsed.', 'OV'),
        ('1.1.17.b', 'G:1.1.17', 'Ühendused on valesti reguleeritud.', 'OV'),
        ('1.1.17.c', 'G:1.1.17', 'Regulaator on kinni kiilunud või ei tööta (ABS toimib). Regulaator on kinni kiilunud või ei tööta.', 'OV,EOV'),
        ('1.1.17.d', 'G:1.1.17', 'Regulaator puudub (kui on nõutud).', 'EOV'),
        ('1.1.17.e', 'G:1.1.17', 'Andmesilt puudub.', 'VO'),
        ('1.1.17.f', 'G:1.1.17', 'Andmed on loetamatud või ei vasta nõuetele.', 'VO'),
        ('G:1.1.18', 'G:1.1', 'Kulumise kompensaatorid ja näiturid', ''),
        ('1.1.18.a', 'G:1.1.18', 'Kompensaator on kahjustunud, kinni kiilunud või liigub valesti, on ülemäärselt kulunud või valesti reguleeritud.', 'OV'),
        ('1.1.18.b', 'G:1.1.18', 'Kompensaator on defektne.', 'OV'),
        ('1.1.18.c', 'G:1.1.18', 'Kompensaator on valesti paigaldatud või asendatud.', 'OV'),
        ('G:1.1.19', 'G:1.1', 'Aeglustisüsteem (kui see on paigaldatud või nõutav)', ''),
        ('1.1.19.a', 'G:1.1.19', 'Ühendused või kinnitused on ebakindlad. Toimimine on häiritud.', 'VO,OV'),
        ('1.1.19.b', 'G:1.1.19', 'Süsteem on ilmselt defektne või puudub.', 'OV'),
        ('G:1.1.20', 'G:1.1', 'Haagisepidurite automaatne rakendumine', ''),
        ('1.1.20', 'G:1.1.20', 'Ühenduse lahtiühendamisel ei rakendu haagisepidur automaatselt.', 'EOV'),
        ('G:1.1.21', 'G:1.1', 'Kogu pidurisüsteem', ''),
        ('1.1.21.a', 'G:1.1.21', 'Muud süsteemi seadmed (näiteks jäätumisvastane pump, õhukuivati jms) on väliselt kahjustatud või ülemäära roostes, nii et see kahjustab pidurisüsteemi. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('1.1.21.b', 'G:1.1.21', 'Õhu või antifriisi leke. Mõjutab süsteemi toimimist.', 'VO,OV'),
        ('1.1.21.c', 'G:1.1.21', 'Mis tahes komponent on ebakindel või valesti paigaldatud.', 'OV'),
        ('1.1.21.d', 'G:1.1.21', 'Mis tahes komponendi ohtlik muudatus. Pidurdustõhusus on halvenenud.', 'OV,EOV'),
        ('G:1.1.22', 'G:1.1', 'Katseühendused (kui need on paigaldatud või nõutavad)', ''),
        ('1.1.22', 'G:1.1.22', 'Puudub.', 'OV'),
        ('G:1.1.23', 'G:1.1', 'Pealejooksupidur', ''),
        ('1.1.23', 'G:1.1.23', 'Ebapiisav tõhusus.', 'OV'),
        ('G:1.2', '1', 'Sõidupiduri toimimine ja tõhusus', ''),
        ('G:1.2.1', 'G:1.2', 'Toimimine (E)', ''),
        ('1.2.1.a', 'G:1.2.1', 'Ühe või enama ratta pidurdusjõud on ebapiisav. Ühe või enama ratta pidurdusjõud puudub.', 'OV,EOV'),
        ('1.2.1.b', 'G:1.2.1', 'Mis tahes ratta pidurdusjõud on vähem kui 70 % sama telje teise ratta maksimaalsest mõõdetud pidurdusjõust. Teekatsetuse korral kaldub sõiduk sirgjoonest liigselt kõrvale. Mis tahes ratta pidurdusjõud on vähem kui 50 % sama telje teise ratta maksimaalsest mõõdetud pidurdusjõust.', 'OV,EOV'),
        ('1.2.1.c', 'G:1.2.1', 'Pidurdusjõud ei muutu järk-järgult (blokeerumine).', 'OV'),
        ('1.2.1.d', 'G:1.2.1', 'Mõne ratta pidur rakendub liiga vara või hilja.', 'OV'),
        ('1.2.1.e', 'G:1.2.1', 'Ratta täispöörde jooksul kõigub pidurdusjõud ülemääraselt.', 'OV'),
        ('G:1.2.2', 'G:1.2', 'Tõhusus (E)', ''),
        ('1.2.2', 'G:1.2.2', 'Ei anna vähemalt järgmist minimaalset pidurdustõhusust: M1-, M2- ja M3-kategooria: 50 %. N1-kategooria: 45 %. N2- ja N3-kategooria: 43 %. O3- ja O4-kategooria: 40 %. Saavutatud vähem kui 50 % eespool nimetatud väärtustest.', 'OV,EOV'),
        ('G:1.3', '1', 'Varu-/hädapiduri toimimine ja tõhusus (kui tegemist on eraldi süsteemiga)', ''),
        ('G:1.3.1', 'G:1.3', 'Toimimine (E)', ''),
        ('1.3.1.a', 'G:1.3.1', 'Ühe või enama ratta pidurdusjõud on ebapiisav. Ühe või enama ratta pidurdusjõud puudub.', 'OV,EOV'),
        ('1.3.1.b', 'G:1.3.1', 'Mis tahes ratta pidurdusjõud on vähem kui 70 % sama telje teise ratta maksimaalsest mõõdetud pidurdusjõust. Teekatsetuse korral kaldub sõiduk sirgjoonest liigselt kõrvale. Mis tahes ratta pidurdusjõud on vähem kui 50 % sama telje teise ratta maksimaalsest mõõdetud pidurdusjõust.', 'OV,EOV'),
        ('1.3.1.c', 'G:1.3.1', 'Pidurdusjõud ei muutu järk-järgult (blokeerumine).', 'OV'),
        ('G:1.3.2', 'G:1.3', 'Tõhusus (E)', ''),
        ('1.3.2', 'G:1.3.2', 'Pidurdusjõud on väiksem kui 50 % nõutavast punktis 1.2.2 osutatud sõidupiduri pidurdusjõust registrimassi järgi arvutatuna. Katsetamise ajal saavutatud vähem kui 50 % eespool nimetatud pidurdusjõu väärtustest (sõiduki massi järgi arvutatuna).', 'OV,EOV'),
        ('G:1.4', '1', 'Seisupiduri toimimine ja tõhusus', ''),
        ('G:1.4.1', 'G:1.4', 'Toimimine (E)', ''),
        ('1.4.1', 'G:1.4.1', 'Ühel küljel pidur ei tööta või teekatsetuse korral kaldub sõiduk sirgjoonest liigselt kõrvale. Katsetamise ajal saavutatud vähem kui 50 % punktis 1.4.2 osutatud pidurdusjõu väärtustest (sõiduki massi järgi arvutatuna).', 'OV,EOV'),
        ('G:1.4.2', 'G:1.4', 'Tõhusus (E)', ''),
        ('1.4.2', 'G:1.4.2', 'Kõikide sõidukikategooriate puhul ei ole pidurdusjõud vähemalt 16 % registrimassi järgi arvutatuna või mootorsõidukitel vähemalt 12 % täismassi järgi arvutatuna, kusjuures kohaldatakse neist kahest suuremat. Katsetamise ajal saavutatud vähem kui 50 % eespool nimetatud pidurdusjõu väärtustest (sõiduki massi järgi arvutatuna).', 'OV,EOV'),
        ('G:1.5', '1', 'Aeglustisüsteemi toimimine', ''),
        ('1.5.a', 'G:1.5', 'Pidurdusjõud ei muutu järk-järgult (ei kohaldata mootorpiduri suhtes).', 'OV'),
        ('1.5.b', 'G:1.5', 'Süsteem ei tööta.', 'OV'),
        ('G:1.6', '1', 'Mitteblokeeruv pidurisüsteem (ABS)', ''),
        ('1.6.a', 'G:1.6', 'Hoiatusseadise rike.', 'OV'),
        ('1.6.b', 'G:1.6', 'Hoiatusseadis näitab süsteemi riket.', 'OV'),
        ('1.6.c', 'G:1.6', 'Ratta kiirusandurid puuduvad või on kahjustunud.', 'OV'),
        ('1.6.d', 'G:1.6', 'Juhtmestik on kahjustunud.', 'OV'),
        ('1.6.e', 'G:1.6', 'Muud osad puuduvad või on kahjustunud.', 'OV'),
        ('1.6.f', 'G:1.6', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('G:1.7', '1', 'Elektrooniline pidurisüsteem (EBS)', ''),
        ('1.7.a', 'G:1.7', 'Hoiatusseadise rike.', 'OV'),
        ('1.7.b', 'G:1.7', 'Hoiatusseadis näitab süsteemi riket.', 'OV'),
        ('1.7.c', 'G:1.7', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('1.7.d', 'G:1.7', 'Vedava sõiduki ja haagise vaheline ühendus ei vasta nõuetele või puudub.', 'EOV'),
        ('G:1.8', '1', 'Pidurivedelik', ''),
        ('1.8', 'G:1.8', 'Pidurivedelik on saastunud või settinud. Ilmne tõrke tekkimise oht.', 'OV,EOV'),
        ('2', '', 'Rooliseade', ''),
        ('G:2.1', '2', 'Mehaaniline seisund', ''),
        ('G:2.1.1', 'G:2.1', 'Rooliseadme seisund', ''),
        ('2.1.1.a', 'G:2.1.1', 'Hammassektorvõll on väändunud või selle tihvtid on kulunud. Mõjutab toimimist.', 'OV,EOV'),
        ('2.1.1.b', 'G:2.1.1', 'Hammassektorvõll on ülemääraselt kulunud. Mõjutab toimimist.', 'OV,EOV'),
        ('2.1.1.c', 'G:2.1.1', 'Hammassektorvõlli ülemäärane liikumine. Mõjutab toimimist.', 'OV,EOV'),
        ('2.1.1.d', 'G:2.1.1', 'Leke. Tilkade teke.', 'OV,EOV'),
        ('G:2.1.2', 'G:2.1', 'Rooliseadme korpuse kinnitus', ''),
        ('2.1.2.a', 'G:2.1.2', 'Rooliseadme korpus ei ole nõuetekohaselt kinnitatud. Kinnitused on ohtlikult lahti või esineb nähtav liikumine šassii/kere suhtes.', 'OV,EOV'),
        ('2.1.2.b', 'G:2.1.2', 'Kinnitusavad šassiil on välja veninud. Kinnitused on olulisel määral mõjutatud.', 'OV,EOV'),
        ('2.1.2.c', 'G:2.1.2', 'Kinnituspoldid puuduvad või on purunenud. Kinnitused on olulisel määral mõjutatud.', 'OV,EOV'),
        ('2.1.2.d', 'G:2.1.2', 'Rooliseadme korpus on mõranenud. Korpuse stabiilsus või kinnitus on kahjustunud.', 'OV,EOV'),
        ('G:2.1.3', 'G:2.1', 'Roolihoovastiku seisund', ''),
        ('2.1.3.a', 'G:2.1.3', 'Komponendid, mis peaksid olema kohtkindlad, liiguvad üksteise suhtes. Ülemäärne liikumine või tõenäoline lahtitulek.', 'OV,EOV'),
        ('2.1.3.b', 'G:2.1.3', 'Liigendid on ülemääraselt kulunud. Väga tõsine lahtituleku oht.', 'OV,EOV'),
        ('2.1.3.c', 'G:2.1.3', 'Teatav komponent on mõranenud või deformeerunud. Mõjutab toimimist.', 'OV,EOV'),
        ('2.1.3.d', 'G:2.1.3', 'Puuduvad lukustusseadmed.', 'OV'),
        ('2.1.3.e', 'G:2.1.3', 'Komponendid on eritelgsed (nt rööpvarras või juhtvarras).', 'OV'),
        ('2.1.3.f', 'G:2.1.3', 'Ohtlik muudatus. Mõjutab toimimist.', 'OV,EOV'),
        ('2.1.3.g', 'G:2.1.3', 'Tolmukaitse on kahjustunud või halvenenud seisundis. Tolmukaitse puudub või on oluliselt halvenenud seisundis.', 'VO,OV'),
        ('G:2.1.4', 'G:2.1', 'Roolihoovastiku toimimine', ''),
        ('2.1.4.a', 'G:2.1.4', 'Liikuv roolihoovastik kahjustab šassii kohtkindlat osa.', 'OV'),
        ('2.1.4.b', 'G:2.1.4', 'Rooli piirajad ei tööta või puuduvad.', 'OV'),
        ('G:2.1.5', 'G:2.1', 'Roolivõimendi', ''),
        ('2.1.5.a', 'G:2.1.5', 'Vedelikuleke.', 'OV'),
        ('2.1.5.b', 'G:2.1.5', 'Vedelikku ei ole piisavalt (tase allpool miinimummärki). Ebapiisav mahuti.', 'OV,EOV'),
        ('2.1.5.c', 'G:2.1.5', 'Mehhanism ei tööta. Mõjutab roolimist.', 'OV,EOV'),
        ('2.1.5.d', 'G:2.1.5', 'Mehhanism on mõranenud või ebakindel. Mõjutab roolimist.', 'OV,EOV'),
        ('2.1.5.e', 'G:2.1.5', 'Komponendid on eritelgsed või kahjustunud. Mõjutab roolimist.', 'OV,EOV'),
        ('2.1.5.f', 'G:2.1.5', 'Ohtlik muudatus. Mõjutab roolimist.', 'OV,EOV'),
        ('2.1.5.g', 'G:2.1.5', 'Trossid/voolikud on kahjustunud või ülemääraselt korrodeerunud. Mõjutab roolimist.', 'OV,EOV'),
        ('G:2.2', '2', 'Rooliratas, roolisammas ja juhtraud', ''),
        ('G:2.2.1', 'G:2.2', 'Rooliratta seisund', ''),
        ('2.2.1.a', 'G:2.2.1', 'Rooliratas ja -sammas liiguvad üksteise suhtes – kinnitus on lõtv. Väga tõsine lahtituleku oht.', 'OV,EOV'),
        ('2.2.1.b', 'G:2.2.1', 'Roolirattarummul puudub kinnitusseade. Väga tõsine lahtituleku oht.', 'OV,EOV'),
        ('2.2.1.c', 'G:2.2.1', 'Roolirattarumm, -rõngas või kodarad on mõranenud või lahti tulnud. Väga tõsine lahtituleku oht.', 'OV,EOV'),
        ('2.2.1.d', 'G:2.2.1', 'Ohtlik muudatus.', 'OV'),
        ('G:2.2.2', 'G:2.2', 'Roolisammas ja juhtimissüsteemi amortisaatorid', ''),
        ('2.2.2.a', 'G:2.2.2', 'Rooliratta keskme ülemäärane liikumine üles või alla.', 'OV'),
        ('2.2.2.b', 'G:2.2.2', 'Roolisamba ülemise osa ülemäärane liikumine radiaalselt samba telje suhtes.', 'OV'),
        ('2.2.2.c', 'G:2.2.2', 'Painduvad ühendused on kahjustunud.', 'OV'),
        ('2.2.2.d', 'G:2.2.2', 'Kinnitus on defektne. Väga tõsine lahtituleku oht.', 'OV,EOV'),
        ('2.2.2.e', 'G:2.2.2', 'Ohtlik muudatus', 'EOV'),
        ('G:2.3', '2', 'Rooli vabakäik', ''),
        ('2.3', 'G:2.3', 'Rooli vabakäik on ettenähtust suurem (näiteks roolirattarõnga teatav punkt liigub rohkem kui ühe viiendiku ulatuses rooliratta läbimõõdust) või ei vasta nõuetele. Mõjutab ohutut roolimist.', 'OV,EOV'),
        ('G:2.4', '2', 'Rataste kokku- või lahkujooks (X)', ''),
        ('2.4', 'G:2.4', 'Kokku- või lahkujooks ei vasta silmanähtavalt nõuetele. Mõjutab otsesõitu; suunastabiilsus on halvenenud.', 'VO,OV'),
        ('G:2.5', '2', 'Haagise pöördtelje pöördlaud', ''),
        ('2.5.a', 'G:2.5', 'Komponent on kergelt kahjustunud. Komponent on tugevalt kahjustunud või mõranenud.', 'OV,EOV'),
        ('2.5.b', 'G:2.5', 'Ülemäärane lõtk. Mõjutab otsesõitu; suunastabiilsus on halvenenud.', 'OV,EOV'),
        ('2.5.c', 'G:2.5', 'Kinnitus on defektne. Kinnitus on olulisel määral kahjustunud.', 'OV,EOV'),
        ('G:2.6', '2', 'Elektrooniline roolivõimendi (EPS)', ''),
        ('2.6.a', 'G:2.6', 'EPSi rikkeindikaator näitab süsteemis tõrget.', 'OV'),
        ('2.6.b', 'G:2.6', 'Roolivõimendi ei tööta.', 'OV'),
        ('2.6.c', 'G:2.6', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('3', '', 'Nähtavus', ''),
        ('G:3.1', '3', 'Vaateväli', ''),
        ('3.1', 'G:3.1', 'Takistused juhi vaateväljas, mis mõjutavad oluliselt nähtavust ettepoole või külgedele (väljaspool klaasipuhastite puhastatavat ala). Klaasipuhastite puhastatav ala on mõjutatud või välispeeglid ei ole nähtavad.', 'VO,OV'),
        ('G:3.2', '3', 'Klaasi seisund', ''),
        ('3.2.a', 'G:3.2', 'Klaas või läbipaistev esipaneel (kui see on lubatud) on mõranenud või värvi muutnud (väljaspool klaasipuhastite puhastatavat ala). Klaasipuhastite puhastatav ala on mõjutatud või välispeeglid ei ole nähtavad.', 'VO,OV'),
        ('3.2.b', 'G:3.2', 'Klaas või läbipaistev esipaneel (sealhulgas peegel- või toonkilega kaetud klaas), mis ei vasta nõuetes esitatud spetsifikatsioonidele (väljaspool klaasipuhastite puhastatavat ala). Klaasipuhastite puhastatav ala on mõjutatud või välispeeglid ei ole nähtavad.', 'VO,OV'),
        ('3.2.c', 'G:3.2', 'Klaasi või läbipaistva esipaneeli seisund ei ole vastuvõetav. Nähtavus läbi klaasipuhastite puhastatava ala on tugevalt mõjutatud.', 'OV,EOV'),
        ('G:3.3', '3', 'Tahavaatepeeglid või -seadmed', ''),
        ('3.3.a', 'G:3.3', 'Peegel või seade puudub või ei ole paigaldatud vastavalt nõuetele (olemas on vähemalt kaks tahavaateseadet). Olemas on vähem kui kaks tahavaateseadet.', 'VO,OV'),
        ('3.3.b', 'G:3.3', 'Peegel või seade on kergelt kahjustunud või lahti tulnud. Peegel või seade ei tööta, on tugevalt kahjustunud, lahti tulnud või ebakindel.', 'VO,OV'),
        ('3.3.c', 'G:3.3', 'Vajalik vaateväli ei ole hõlmatud.', 'OV'),
        ('G:3.4', '3', 'Klaasipuhastid', ''),
        ('3.4.a', 'G:3.4', 'Puhastid ei tööta või puuduvad.', 'OV'),
        ('3.4.b', 'G:3.4', 'Puhasti hari on defektne. Puhasti hari puudub või on silmanähtavalt defektne.', 'VO,OV'),
        ('G:3.5', '3', 'Klaasipesurid', ''),
        ('3.5', 'G:3.5', 'Pesurid ei tööta nõuetekohaselt (puudub pesemisvedelik, kuid pump töötab, või veejuga on valesti suunatud). Pesurid ei tööta.', 'VO,OV'),
        ('G:3.6', '3', 'Niiskuse eemaldamise süsteem (X)', ''),
        ('3.6', 'G:3.6', 'Süsteem ei tööta või on silmanähtavalt defektne.', 'VO'),
        ('4', '', 'Valgustusseadmed ja elektrisüsteemi osad', ''),
        ('G:4.1', '4', 'Esilaternad', ''),
        ('G:4.1.1', 'G:4.1', 'Seisund ja toimimine', ''),
        ('4.1.1.a', 'G:4.1.1', 'Valgusti/valgusallikas on defektne või puudub (mitu valgustit/valgusallikat; LED-valgusti puhul ei tööta vähem kui 1/3). Üks valgusti/valgusallikas; LED-valgusti puhul on nähtavus olulisel määral mõjutatud.', 'VO,OV'),
        ('4.1.1.b', 'G:4.1.1', 'Projektsioonisüsteem (reflektor ja hajutiklaas) on kergelt defektne. Projektsioonisüsteem (reflektor ja hajutiklaas) on tugevalt defektne või puudub.', 'VO,OV'),
        ('4.1.1.c', 'G:4.1.1', 'Latern ei ole kindlalt kinnitatud.', 'OV'),
        ('G:4.1.2', 'G:4.1', 'Reguleeritus', ''),
        ('4.1.2.a', 'G:4.1.2', 'Esilatern on selgelt valesti reguleeritud.', 'OV'),
        ('4.1.2.b', 'G:4.1.2', 'Valgusallikas on valesti paigaldatud.', 'VO'),
        ('G:4.1.3', 'G:4.1', 'Lülitid', ''),
        ('4.1.3.a', 'G:4.1.3', 'Lüliti ei tööta nõuetele vastavalt (ühel ja samal ajal põlevate esilaternate arv). Lubatud piirmäära ületav valgustugevus sõidukist ettepoole.', 'VO,OV'),
        ('4.1.3.b', 'G:4.1.3', 'Kontrollseadise talitlus on häiritud.', 'OV'),
        ('G:4.1.4', 'G:4.1', 'Vastavus nõuetele', ''),
        ('4.1.4.a', 'G:4.1.4', 'Latern, selle valgusvihu värvus, asend, valgustugevus või märgistus ei vasta nõuetele.', 'OV'),
        ('4.1.4.b', 'G:4.1.4', 'Miski hajutiklaasil või valgusallikal vähendab ilmselgelt valgustugevust või muudab valguse värvi.', 'OV'),
        ('4.1.4.c', 'G:4.1.4', 'Valgusallikas ja latern ei ühildu omavahel.', 'OV'),
        ('G:4.1.5', 'G:4.1', 'Reguleerimisseadmed (kui need on kohustuslikud)', ''),
        ('4.1.5.a', 'G:4.1.5', 'Seade ei tööta.', 'OV'),
        ('4.1.5.b', 'G:4.1.5', 'Käsijuhtimisega seadet ei saa juhikohalt käitada.', 'OV'),
        ('G:4.1.6', 'G:4.1', 'Esilaternate puhastusseade (kui see on kohustuslik)', ''),
        ('4.1.6', 'G:4.1.6', 'Seade ei tööta. Gaaslahenduslampide puhul.', 'VO,OV'),
        ('G:4.2', '4', 'Eesmised ja tagumised äärelaternad, külgmised äärelaternad, ülemised äärelaternad ning päevasõidulaternad', ''),
        ('G:4.2.1', 'G:4.2', 'Seisund ja toimimine', ''),
        ('4.2.1.a', 'G:4.2.1', 'Valgusallikas on defektne.', 'OV'),
        ('4.2.1.b', 'G:4.2.1', 'Hajutiklaas on defektne.', 'OV'),
        ('4.2.1.c', 'G:4.2.1', 'Latern ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku oht.', 'VO,OV'),
        ('G:4.2.2', 'G:4.2', 'Lülitamine', ''),
        ('4.2.2.a', 'G:4.2.2', 'Lüliti ei tööta vastavalt nõuetele. Tagumisi äärelaternaid ja külgmisi äärelaternaid on võimalik välja lülitada esilaternate põlemise ajal.', 'OV'),
        ('4.2.2.b', 'G:4.2.2', 'Kontrollseadise talitlus on häiritud.', 'OV'),
        ('G:4.2.3', 'G:4.2', 'Vastavus nõuetele', ''),
        ('4.2.3.a', 'G:4.2.3', 'Latern, selle valgusvihu värvus, asend, valgustugevus või märgistus ei vasta nõuetele. Kiirgab ettepoole punast valgust või tahapoole valget valgust; valgustugevus on oluliselt vähenenud.', 'VO,OV'),
        ('4.2.3.b', 'G:4.2.3', 'Miski hajutiklaasil või valgusallikal vähendab valgustugevust või muudab valguse värvi. Kiirgab ettepoole punast valgust või tahapoole valget valgust; valgustugevus on oluliselt vähenenud.', 'VO,OV'),
        ('G:4.3', '4', 'Pidurilaternad', ''),
        ('G:4.3.1', 'G:4.3', 'Seisund ja toimimine', ''),
        ('4.3.1.a', 'G:4.3.1', 'Valgusallikas on defektne (mitu valgusallikat; LED-valgusti puhul ei tööta vähem kui 1/3). Üks valgusallikas; LED-valgusti puhul töötab vähem kui 2/3. Ükski valgusallikas ei toimi.', 'VO,OV,EOV'),
        ('4.3.1.b', 'G:4.3.1', 'Laternaklaas on kergelt defektne (ei mõjuta kiiratavat valgust). Laternaklaas on tugevalt defektne (mõjutab kiiratavat valgust).', 'VO,OV'),
        ('4.3.1.c', 'G:4.3.1', 'Latern ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku oht.', 'VO,OV'),
        ('G:4.3.2', 'G:4.3', 'Lülitamine', ''),
        ('4.3.2.a', 'G:4.3.2', 'Lüliti ei tööta vastavalt nõuetele. Toimimine hilinemisega. Lüliti ei tööta üldse.', 'VO,OV,EOV'),
        ('4.3.2.b', 'G:4.3.2', 'Kontrollseadise talitlus on häiritud.', 'OV'),
        ('G:4.3.3', 'G:4.3', 'Vastavus nõuetele.', ''),
        ('4.3.3', 'G:4.3.3', 'Latern, selle valgusvihu värvus, asend, valgustugevus või märgistus ei vasta nõuetele. Kiirgab tahapoole valget valgust; valgustugevus on oluliselt vähenenud.', 'VO,OV'),
        ('G:4.4', '4', 'Suuna- ja ohulaternad', ''),
        ('G:4.4.1', 'G:4.4', 'Seisund ja toimimine', ''),
        ('4.4.1.a', 'G:4.4.1', 'Valgusallikas on defektne (mitu valgusallikat; LED-valgusti puhul ei tööta vähem kui 1/3). Üks valgusallikas; LED-valgusti puhul töötab vähem kui 2/3.', 'VO,OV'),
        ('4.4.1.b', 'G:4.4.1', 'Laternaklaas on kergelt defektne (ei mõjuta kiiratavat valgust). Laternaklaas on tugevalt defektne (mõjutab kiiratavat valgust).', 'VO,OV'),
        ('4.4.1.c', 'G:4.4.1', 'Latern ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku oht.', 'VO,OV'),
        ('G:4.4.2', 'G:4.4', 'Lülitamine', ''),
        ('4.4.2', 'G:4.4.2', 'Lüliti ei tööta vastavalt nõuetele. Lüliti ei tööta üldse.', 'VO,OV'),
        ('G:4.4.3', 'G:4.4', 'Vastavus nõuetele.', ''),
        ('4.4.3', 'G:4.4.3', 'Latern, selle valgusvihu värvus, asend, valgustugevus või märgistus ei vasta nõuetele.', 'OV'),
        ('G:4.4.4', 'G:4.4', 'Vilkumissagedus', ''),
        ('4.4.4', 'G:4.4.4', 'Vilkumissagedus ei vasta nõuetele (sagedus erineb nõuetest rohkem kui 25 %).', 'VO'),
        ('G:4.5', '4', 'Eesmised ja tagumised udulaternad', ''),
        ('G:4.5.1', 'G:4.5', 'Seisund ja toimimine', ''),
        ('4.5.1.a', 'G:4.5.1', 'Valgusallikas on defektne (mitu valgusallikat; LED-valgusti puhul ei tööta vähem kui 1/3). Üks valgusallikas; LED-valgusti puhul töötab vähem kui 2/3.', 'VO,OV'),
        ('4.5.1.b', 'G:4.5.1', 'Laternaklaas on kergelt defektne (ei mõjuta kiiratavat valgust). Laternaklaas on tugevalt defektne (mõjutab kiiratavat valgust).', 'VO,OV'),
        ('4.5.1.c', 'G:4.5.1', 'Latern ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku või vastutulevate sõidukite pimestamise oht.', 'VO,OV'),
        ('G:4.5.2', 'G:4.5', 'Reguleeritus (X)', ''),
        ('4.5.2', 'G:4.5.2', 'Valgusvihu valguse ja varju piirjoone korral on eesmine udulatern horisontaalselt valesti reguleeritud (valguse ja varju piirjoon on liiga madalal). Valguse ja varju piirjoon on eesmiste lähitulelaternate omast kõrgemal.', 'VO,OV'),
        ('G:4.5.3', 'G:4.5', 'Lülitamine', ''),
        ('4.5.3', 'G:4.5.3', 'Lüliti ei tööta vastavalt nõuetele. Ei toimi.', 'VO,OV'),
        ('G:4.5.4', 'G:4.5', 'Vastavus nõuetele.', ''),
        ('4.5.4.a', 'G:4.5.4', 'Latern, selle valgusvihu värvus, asend, valgustugevus või märgistus ei vasta nõuetele.', 'OV'),
        ('4.5.4.b', 'G:4.5.4', 'Süsteem ei tööta vastavalt nõuetele.', 'VO'),
        ('G:4.6', '4', 'Tagurduslaternad', ''),
        ('G:4.6.1', 'G:4.6', 'Seisund ja toimimine', ''),
        ('4.6.1.a', 'G:4.6.1', 'Valgusallikas on defektne.', 'VO'),
        ('4.6.1.b', 'G:4.6.1', 'Laternaklaas on defektne.', 'VO'),
        ('4.6.1.c', 'G:4.6.1', 'Latern ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku oht.', 'VO,OV'),
        ('G:4.6.2', 'G:4.6', 'Vastavus nõuetele', ''),
        ('4.6.2.a', 'G:4.6.2', 'Latern, selle valgusvihu värvus, asend, valgustugevus või märgistus ei vasta nõuetele.', 'OV'),
        ('4.6.2.b', 'G:4.6.2', 'Süsteem ei tööta vastavalt nõuetele.', 'OV'),
        ('G:4.6.3', 'G:4.6', 'Lülitid', ''),
        ('4.6.3', 'G:4.6.3', 'Lüliti ei tööta vastavalt nõuetele. Tagurdustule saab sisse lülitada, kui tagasikäik ei ole sisse lülitatud.', 'VO,OV'),
        ('G:4.7', '4', 'Tagumine numbrilatern', ''),
        ('G:4.7.1', 'G:4.7', 'Seisund ja toimimine', ''),
        ('4.7.1.a', 'G:4.7.1', 'Latern heidab otsevalgust või valget valgust taha.', 'VO'),
        ('4.7.1.b', 'G:4.7.1', 'Valgusallikas on defektne (mitu valgusallikat). Valgusallikas on defektne (üks valgusallikas).', 'VO,OV'),
        ('4.7.1.c', 'G:4.7.1', 'Latern ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku oht.', 'VO,OV'),
        ('G:4.7.2', 'G:4.7', 'Vastavus nõuetele', ''),
        ('4.7.2', 'G:4.7.2', 'Süsteem ei tööta vastavalt nõuetele.', 'VO'),
        ('G:4.8', '4', 'Helkurid, nähtavamaks tegemise märgistus (valgustpeegeldav) ja tagumised märgistusplaadid', ''),
        ('G:4.8.1', 'G:4.8', 'Seisund', ''),
        ('4.8.1.a', 'G:4.8.1', 'Helkurseadmed on defektsed või kahjustunud. Mõjutab peegeldust.', 'VO,OV'),
        ('4.8.1.b', 'G:4.8.1', 'Helkur ei ole kindlalt kinnitatud. Võib küljest ära kukkuda.', 'VO,OV'),
        ('G:4.8.2', 'G:4.8', 'Vastavus nõuetele', ''),
        ('4.8.2', 'G:4.8.2', 'Seade, selle peegeldatav värv või asend ei vasta nõuetele. Seade puudub või peegeldab ettepoole punast või tahapoole valget värvust.', 'OV,EOV'),
        ('G:4.9', '4', 'Valgustusseadmete kohustuslikud märgulambid', ''),
        ('G:4.9.1', 'G:4.9', 'Seisund ja toimimine', ''),
        ('4.9.1', 'G:4.9.1', 'Seade ei tööta. Seade ei tööta eesmiste kaugtulede või tagumiste udulaternate puhul.', 'VO,OV'),
        ('G:4.9.2', 'G:4.9', 'Vastavus nõuetele', ''),
        ('4.9.2', 'G:4.9.2', 'Ei vasta nõuetele.', 'VO'),
        ('G:4.10', '4', 'Pukseeriva sõiduki ja haagise või poolhaagise elektriühendused', ''),
        ('4.10.a', 'G:4.10', 'Kohtkindlad komponendid ei ole kindlalt kinnitatud. Pistikupesa on lahti tulnud.', 'VO,OV'),
        ('4.10.b', 'G:4.10', 'Isolatsioon on kahjustunud või selle seisund on halvenenud. Esineb lühise tekke oht.', 'VO,OV'),
        ('4.10.c', 'G:4.10', 'Haagise või pukseeriva sõiduki elektriühendused ei toimi nõuetekohaselt. Haagise pidurituled ei tööta.', 'OV,EOV'),
        ('G:4.11', '4', 'Elektrijuhtmestik', ''),
        ('4.11.a', 'G:4.11', 'Juhtmestik on halvasti kinnitatud või ei ole piisavalt kaitstud. Kinnitused on lahti, puutuvad vastu teravaid servi, ühendused võivad lahti tulla. Juhtmestik võib puutuda kokku kuumade või pöörlevate osade või maapinnaga, ühendused on lahti (piduri- või roolisüsteemi jaoks olulised osad).', 'VO,OV,EOV'),
        ('4.11.b', 'G:4.11', 'Juhtmestik on kergelt kahjustunud. Juhtmestik on tugevalt kahjustunud. Juhtmestik on äärmiselt kahjustunud (piduri- või roolisüsteemi jaoks olulised osad).', 'VO,OV,EOV'),
        ('4.11.c', 'G:4.11', 'Isolatsioon on kahjustunud või selle seisund on halvenenud. Esineb lühise tekke oht. Suur tule-/sädelusoht.', 'VO,OV,EOV'),
        ('G:4.12', '4', 'Mittekohustuslikud laternad ja helkurid (X)', ''),
        ('4.12.a', 'G:4.12', 'Laterna/helkuri paigaldus ei vasta nõuetele. Kiirgab/peegeldab ettepoole punast valgust või tahapoole valget valgust.', 'VO,OV'),
        ('4.12.b', 'G:4.12', 'Latern ei tööta vastavalt nõuetele. Ühel ja samal ajal töötavate esilaternate valgustugevus on lubatust suurem; kiirgab ettepoole punast valgust või tahapoole valget valgust.', 'VO,OV'),
        ('4.12.c', 'G:4.12', 'Latern/helkur ei ole kindlalt kinnitatud. Väga tõsine küljest äratuleku oht.', 'VO,OV'),
        ('G:4.13', '4', 'Aku(d)', ''),
        ('4.13.a', 'G:4.13', 'Aku on ebakindel. Ei ole õigesti kinnitatud; esineb lühise tekke oht.', 'VO,OV'),
        ('4.13.b', 'G:4.13', 'Aku lekib. Ohtlike ainete leke.', 'VO,OV'),
        ('4.13.c', 'G:4.13', 'Defektne lüliti (kui lüliti on nõutav).', 'OV'),
        ('4.13.d', 'G:4.13', 'Defektsed kaitsmed (kui kaitsmed on nõutavad).', 'OV'),
        ('4.13.e', 'G:4.13', 'Ebasobiv ventilatsioon (kui ventilatsioon on nõutav).', 'OV'),
        ('5', '', 'Teljed, veljed, rehvid, vedrustus', ''),
        ('G:5.1', '5', 'Teljed', ''),
        ('G:5.1.1', 'G:5.1', 'Teljed (+E)', ''),
        ('5.1.1.a', 'G:5.1.1', 'Telg on mõranenud või deformeerunud.', 'EOV'),
        ('5.1.1.b', 'G:5.1.1', 'Telg on sõiduki külge kinnitatud ebakindlalt. Stabiilsus on halvenenud, mõjutab toimimist: ülemäärane liikumine kinnituste suhtes.', 'OV,EOV'),
        ('5.1.1.c', 'G:5.1.1', 'Ohtlik muudatus. Stabiilsus on halvenenud, mõjutab toimimist, liiga lähedal muudele sõidukiosadele või maapinnale.', 'OV,EOV'),
        ('G:5.1.2', 'G:5.1', 'Käänmikud (+E)', ''),
        ('5.1.2.a', 'G:5.1.2', 'Käänmik on mõranenud.', 'EOV'),
        ('5.1.2.b', 'G:5.1.2', 'Kuulliigend ja/või puksid on ülemäära kulunud. Võib lahti tulla; suunastabiilsus on halvenenud.', 'OV,EOV'),
        ('5.1.2.c', 'G:5.1.2', 'Ülemäärane liikumine teljetala ja käänmiku vahel. Võib lahti tulla; suunastabiilsus on halvenenud.', 'OV,EOV'),
        ('5.1.2.d', 'G:5.1.2', 'Käänmikupolt on teljel lahti tulnud. Võib lahti tulla; suunastabiilsus on halvenenud.', 'OV,EOV'),
        ('G:5.1.3', 'G:5.1', 'Rattalaagrid (+E)', ''),
        ('5.1.3.a', 'G:5.1.3', 'Ülemäärane lõtk rattalaagris. Suunastabiilsus on halvenenud; purunemisoht.', 'OV,EOV'),
        ('5.1.3.b', 'G:5.1.3', 'Rattalaager on liiga tihke, kinni kiilunud. Ülekuumenemisoht; purunemisoht.', 'OV,EOV'),
        ('G:5.2', '5', 'Veljed ja rehvid', ''),
        ('G:5.2.1', 'G:5.2', 'Rattarumm', ''),
        ('5.2.1.a', 'G:5.2.1', 'Mis tahes rattamutrid või -poldid puuduvad või on lahti tulnud. Puuduv kinnitus või kinnitus lahti ulatuses, mis mõjutab väga tõsiselt liiklusohutust.', 'OV,EOV'),
        ('5.2.1.b', 'G:5.2.1', 'Rumm on kulunud või kahjustunud. Rumm on kulunud või kahjustunud nii, et see mõjutab velgede kinnitust.', 'OV,EOV'),
        ('G:5.2.2', 'G:5.2', 'Veljed', ''),
        ('5.2.2.a', 'G:5.2.2', 'Mis tahes mõra või defekt keevises.', 'EOV'),
        ('5.2.2.b', 'G:5.2.2', 'Rehvide lukustusrõngad ei ole nõuetekohaselt paigaldatud. Võivad küljest ära kukkuda.', 'OV,EOV'),
        ('5.2.2.c', 'G:5.2.2', 'Velg on tõsiselt deformeerunud või kulunud. Mõjutab kinnitust rummuga; mõjutab kinnitust rehviga.', 'OV,EOV'),
        ('5.2.2.d', 'G:5.2.2', 'Velje suurus, tehniline konstruktsioon, kokkusobivus või tüüp ei vasta nõuetele ning mõjutab liiklusohutust.', 'OV'),
        ('G:5.2.3', 'G:5.2', 'Rehvid', ''),
        ('5.2.3.a', 'G:5.2.3', 'Rehvi suurus, koormustaluvus, tüübikinnitusmärk või kiiruskategooria ei vasta nõuetele ning mõjutab liiklusohutust. Kasutamiseks ebapiisav koormustaluvus või kiiruskategooria, rehv puutub kokku sõiduki muude liikumatute osadega, mis halvendab ohutut juhtimist.', 'OV,EOV'),
        ('5.2.3.b', 'G:5.2.3', 'Samal teljel asuvate rataste või topeltrataste rehvid on erineva suurusega.', 'OV'),
        ('5.2.3.c', 'G:5.2.3', 'Samal teljel asuvad rehvid on erineva konstruktsiooniga (radiaal-/diagonaalrehvid).', 'OV'),
        ('5.2.3.d', 'G:5.2.3', 'Mis tahes tõsine kahjustus või sisselõige rehvis. Koort on nähtav või kahjustatud.', 'OV,EOV'),
        ('5.2.3.e', 'G:5.2.3', 'Turvise kulumise märgid muutuvad nähtavaks. Rehvimustri sügavus ei vasta nõuetele.', 'OV,EOV'),
        ('5.2.3.f', 'G:5.2.3', 'Rehv hõõrdub teiste komponentide vastu (painduvad porikaitsed). Rehv hõõrdub teiste komponentide vastu (ei mõjuta ohutut juhtimist).', 'VO,OV'),
        ('5.2.3.g', 'G:5.2.3', 'Lõigatud mustriga rehvid ei vasta nõuetele. Koorti kaitsekiht on kahjustatud.', 'OV,EOV'),
        ('G:5.3', '5', 'Vedrustus', ''),
        ('G:5.3.1', 'G:5.3', 'Vedrud ja stabilisaator (+E)', ''),
        ('5.3.1.a', 'G:5.3.1', 'Vedrud on šassii või telje külge kinnitatud ebakindlalt. Suhteline liikumine on nähtav, kinnitused on väga suurel määral lahti.', 'OV,EOV'),
        ('5.3.1.b', 'G:5.3.1', 'Vedru osa on kahjustunud või mõranenud. Põhivedru (vedruleht) või lisalehed on väga tõsiselt mõjutatud.', 'OV,EOV'),
        ('5.3.1.c', 'G:5.3.1', 'Vedru puudub. Põhivedru (vedruleht) või lisalehed on väga tõsiselt mõjutatud.', 'OV,EOV'),
        ('5.3.1.d', 'G:5.3.1', 'Ohtlik muudatus. Liiga lähedal muudele sõidukiosadele; vedrustussüsteem ei toimi.', 'OV,EOV'),
        ('G:5.3.2', 'G:5.3', 'Amortisaatorid', ''),
        ('5.3.2.a', 'G:5.3.2', 'Amortisaatorid on šassii või telje külge kinnitatud ebakindlalt. Amortisaator on lahti.', 'VO,OV'),
        ('5.3.2.b', 'G:5.3.2', 'Tõsise lekke või rikke märkidega kahjustunud amortisaator.', 'OV'),
        ('5.3.2.c', 'G:5.3.2', 'Amortisaator puudub.', 'OV'),
        ('G:5.3.3', 'G:5.3', 'Pöördtorud, reaktiivvardad, õõtshargid ja -hoovad (+E)', ''),
        ('5.3.3.a', 'G:5.3.3', 'Komponent on šassii või telje külge kinnitatud ebakindlalt. Võib lahti tulla; suunastabiilsus on halvenenud.', 'OV,EOV'),
        ('5.3.3.b', 'G:5.3.3', 'Komponent on kahjustunud või ülemääraselt korrodeerunud. Mõjutab komponendi stabiilsust või komponent on mõranenud.', 'OV,EOV'),
        ('5.3.3.c', 'G:5.3.3', 'Ohtlik muudatus. Liiga lähedal muudele sõidukiosadele; süsteem ei toimi.', 'OV,EOV'),
        ('G:5.3.4', 'G:5.3', 'Vedrustuse liigendid (+E)', ''),
        ('5.3.4.a', 'G:5.3.4', 'Pöörlipolt ja/või puksid või vedrustuse liigendid on ülemäära kulunud. Võib lahti tulla; suunastabiilsus on halvenenud.', 'OV,EOV'),
        ('5.3.4.b', 'G:5.3.4', 'Tolmukaitse on oluliselt halvenenud seisundis. Tolmukaitse puudub või on mõranenud.', 'VO,OV'),
        ('G:5.3.5', 'G:5.3', 'Õhkvedrustus', ''),
        ('5.3.5.a', 'G:5.3.5', 'Süsteem ei tööta.', 'EOV'),
        ('5.3.5.b', 'G:5.3.5', 'Mis tahes komponent on kahjustunud, halvenenud seisundis või seda on muudetud ning see kahjustab süsteemi toimimist. Mõjutab süsteemi toimimist olulisel määral.', 'OV,EOV'),
        ('5.3.5.c', 'G:5.3.5', 'Kuuldav leke süsteemis.', 'OV'),
        ('5.3.5.d', 'G:5.3.5', 'Ohtlik muudatus.', 'OV'),
        ('6', '', 'Šassii ja selle kinnitused', ''),
        ('G:6.1', '6', 'Šassii või raam ja selle kinnitused', ''),
        ('G:6.1.1', 'G:6.1', 'Üldseisund', ''),
        ('6.1.1.a', 'G:6.1.1', 'Mis tahes piki- või risttala kerge mõranemine või deformeerumine. Mis tahes piki- või risttala tõsine mõranemine või deformeerumine.', 'OV,EOV'),
        ('6.1.1.b', 'G:6.1.1', 'Tugevdusplaadid või kinnitused on ebakindlad. Suurem osa kinnitusi on lahti; osad ei ole piisavalt tugevad.', 'OV,EOV'),
        ('6.1.1.c', 'G:6.1.1', 'Koostu jäikust mõjutav ülemäärane korrosioon. Osad ei ole piisavalt tugevad.', 'OV,EOV'),
        ('G:6.1.2', 'G:6.1', 'Väljalasketorud ja summutid', ''),
        ('6.1.2.a', 'G:6.1.2', 'Heitgaasisüsteem on ebakindel või lekib.', 'OV'),
        ('6.1.2.b', 'G:6.1.2', 'Kabiini või sõitjateruumi tuleb suitsu. Oht sõidukis viibivate isikute tervisele.', 'OV,EOV'),
        ('G:6.1.3', 'G:6.1', 'Kütusepaak ja -torud (sh kütteaine paak ja torud)', ''),
        ('6.1.3.a', 'G:6.1.3', 'Ebaturvaline paak või torud, mis põhjustab suurt tuleohtu.', 'EOV'),
        ('6.1.3.b', 'G:6.1.3', 'Vedelikku lekib, täiteava kork puudub või laseb läbi. Tuleoht; ohtliku materjali ülemäärane kadu.', 'OV,EOV'),
        ('6.1.3.c', 'G:6.1.3', 'Hõõrdunud torud. Kahjustunud torud.', 'VO,OV'),
        ('6.1.3.d', 'G:6.1.3', 'Kütuse korkkraan (kui see on nõutav) ei tööta õigesti.', 'OV'),
        ('6.1.3.e', 'G:6.1.3', 'Tuleoht, mis on tingitud: — kütuselekkest; — ebaõigesti varjestatud kütusepaagist või heitgaasitorustikust; — mootoriruumi seisundist.', 'EOV'),
        ('6.1.3.f', 'G:6.1.3', 'LPG-/CNG-/LNG- või vesinikusüsteem ei vasta nõuetele, süsteemi mis tahes osa on defektne.', 'EOV'),
        ('G:6.1.4', 'G:6.1', 'Kaitserauad, külgmised ja tagumised allasõidutõkked', ''),
        ('6.1.4.a', 'G:6.1.4', 'Komponent on lahti tulnud või kahjustunud ning võib riivamisel või kokkupuutel tekitada vigastusi. Osad võivad küljest ära kukkuda; mõjutab toimimist olulisel määral.', 'OV,EOV'),
        ('6.1.4.b', 'G:6.1.4', 'Seade ei vasta ilmselgelt nõuetele.', 'OV'),
        ('G:6.1.5', 'G:6.1', 'Varuratta kandur (kui see on olemas)', ''),
        ('6.1.5.a', 'G:6.1.5', 'Varuratta kandur ei ole nõuetekohases seisukorras.', 'VO'),
        ('6.1.5.b', 'G:6.1.5', 'Varuratta kandur on mõranenud või ebakindel.', 'OV'),
        ('6.1.5.c', 'G:6.1.5', 'Varuratas ei ole kandurile turvaliselt kinnitatud. Väga tõsine küljest äratuleku oht.', 'OV,EOV'),
        ('G:6.1.6', 'G:6.1', 'Mehaanilised haakeseadmed ja pukseerimisseadised (+E)', ''),
        ('6.1.6.a', 'G:6.1.6', 'Komponent on kahjustunud, defektne või mõranenud (kui seda ei kasutata). Komponent on kahjustunud, defektne või mõranenud (kui seda kasutatakse).', 'OV,EOV'),
        ('6.1.6.b', 'G:6.1.6', 'Komponent on ülemäära kulunud. Allpool kulumispiiri.', 'OV,EOV'),
        ('6.1.6.c', 'G:6.1.6', 'Kinnitus on defektne. Mis tahes kinnitus on lahti; väga tõsine küljest äratuleku oht.', 'OV,EOV'),
        ('6.1.6.d', 'G:6.1.6', 'Mis tahes ohutusseadis puudub või ei tööta õigesti.', 'OV'),
        ('6.1.6.e', 'G:6.1.6', 'Mis tahes haakeseadme näidik ei tööta.', 'OV'),
        ('6.1.6.f', 'G:6.1.6', 'Registreerimismärk või mõni latern on varjatud (kui seda ei kasutata). Registreerimismärk ei ole loetav (kui seadet ei kasutata).', 'VO,OV'),
        ('6.1.6.g', 'G:6.1.6', 'Ohtlik muudatus (teisesed osad). Ohtlik muudatus (põhiosad).', 'OV,EOV'),
        ('6.1.6.h', 'G:6.1.6', 'Haagise ühendus on liiga nõrk või mittevastav või haakeseade ei vasta nõuetele.', 'EOV'),
        ('G:6.1.7', 'G:6.1', 'Jõuülekanne', ''),
        ('6.1.7.a', 'G:6.1.7', 'Kinnituspoldid on lahti tulnud või puuduvad. Kinnituspoldid on lahti tulnud või puuduvad ulatuses, mis ohustab tõsiselt liiklusohutust.', 'OV,EOV'),
        ('6.1.7.b', 'G:6.1.7', 'Ülekandevõlli laagrid on ülemäära kulunud. Väga tõsine lahtituleku või purunemise oht.', 'OV,EOV'),
        ('6.1.7.c', 'G:6.1.7', 'Universaalliigendid või ülekandeketid/-rihmad on ülemäära kulunud. Väga tõsine lahtituleku või purunemise oht.', 'OV,EOV'),
        ('6.1.7.d', 'G:6.1.7', 'Kahjustunud painduvad ühendused. Väga tõsine lahtituleku või purunemise oht.', 'OV,EOV'),
        ('6.1.7.e', 'G:6.1.7', 'Kahjustunud või paindunud võll.', 'OV'),
        ('6.1.7.f', 'G:6.1.7', 'Laagri korpus on mõranenud või ebakindel. Väga tõsine lahtituleku või purunemise oht.', 'OV,EOV'),
        ('6.1.7.g', 'G:6.1.7', 'Tolmukaitse on oluliselt halvenenud seisundis. Tolmukaitse puudub või on mõranenud.', 'VO,OV'),
        ('6.1.7.h', 'G:6.1.7', 'Jõuseadet on ebaseaduslikult muudetud.', 'OV'),
        ('G:6.1.8', 'G:6.1', 'Mootori kinnitused', ''),
        ('6.1.8', 'G:6.1.8', 'Kinnitusdetailid on halvenenud seisundis, silmanähtavalt ja tõsiselt kahjustunud. Kinnitusdetailid on lahti tulnud või mõranenud.', 'OV,EOV'),
        ('G:6.1.9', 'G:6.1', 'Mootori jõudlus (X)', ''),
        ('6.1.9.a', 'G:6.1.9', 'Juhtseadme muutmine, millel on mõju ohutusele ja/või keskkonnale.', 'OV'),
        ('6.1.9.b', 'G:6.1.9', 'Mootori muutmine, millel on mõju ohutusele ja/või keskkonnale.', 'EOV'),
        ('G:6.2', '6', 'Kabiin ja kere', ''),
        ('G:6.2.1', 'G:6.2', 'Seisund', ''),
        ('6.2.1.a', 'G:6.2.1', 'Lahti tulnud või kahjustunud paneel või osa, mis võib tekitada vigastusi. Võib küljest ära kukkuda.', 'OV,EOV'),
        ('6.2.1.b', 'G:6.2.1', 'Ebakindel kerepost. Stabiilsus on halvenenud.', 'OV,EOV'),
        ('6.2.1.c', 'G:6.2.1', 'Mootorisuits või heitgaasid pääsevad kabiini. Oht sõidukis viibivate isikute tervisele.', 'OV,EOV'),
        ('6.2.1.d', 'G:6.2.1', 'Ohtlik muudatus. Liiga lähedal pöörlevatele või liikuvatele osadele ja teele.', 'OV,EOV'),
        ('G:6.2.2', 'G:6.2', 'Paigaldus', ''),
        ('6.2.2.a', 'G:6.2.2', 'Ebakindel kere või kabiin. Mõjutab stabiilsust.', 'OV,EOV'),
        ('6.2.2.b', 'G:6.2.2', 'Kere/kabiin on šassiil silmanähtavalt viltu.', 'OV'),
        ('6.2.2.c', 'G:6.2.2', 'Kere/kabiini kinnitus šassii või risttalade külge on ebakindel või puudub ja kui kinnitus on sümmeetriline. Kere/kabiini kinnitus šassii või risttalade külge on ebakindel või puudub ulatuses, mis ohustab väga tõsiselt liiklusohutust.', 'OV,EOV'),
        ('6.2.2.d', 'G:6.2.2', 'Kinnituskohad on ülemääraselt korrodeerunud. Stabiilsus on halvenenud.', 'OV,EOV'),
        ('G:6.2.3', 'G:6.2', 'Uksed ja ukselukud', ''),
        ('6.2.3.a', 'G:6.2.3', 'Uks ei avane või ei sulgu korralikult.', 'OV'),
        ('6.2.3.b', 'G:6.2.3', 'Uks võib iseenesest avaneda või ei püsi suletuna (lükanduksed). Uks võib iseenesest avaneda või ei püsi suletuna (pöörduksed).', 'OV,EOV'),
        ('6.2.3.c', 'G:6.2.3', 'Uks, hinged, lukud või tugipost on halvenenud seisundis. Uks, hinged, lukud või tugipost on puudu või lahti tulnud.', 'VO,OV'),
        ('G:6.2.4', 'G:6.2', 'Põrand', ''),
        ('6.2.4', 'G:6.2.4', 'Ebakindel või oluliselt halvenenud seisundis põrand. Stabiilsus ei ole piisav.', 'OV,EOV'),
        ('G:6.2.5', 'G:6.2', 'Juhiiste', ''),
        ('6.2.5.a', 'G:6.2.5', 'Istme konstruktsioon on defektne. Iste on lahti tulnud.', 'OV,EOV'),
        ('6.2.5.b', 'G:6.2.5', 'Istme reguleerimise mehhanism ei tööta õigesti. Iste liigub või seljatugi ei ole fikseeritav.', 'OV,EOV'),
        ('G:6.2.6', 'G:6.2', 'Muud istmed', ''),
        ('6.2.6.a', 'G:6.2.6', 'Istmed on defektsed või ebakindlad (teisesed osad). Istmed on defektsed või ebakindlad (põhiosad).', 'VO,OV'),
        ('6.2.6.b', 'G:6.2.6', 'Istmed ei ole paigaldatud vastavalt nõuetele. Istmeid on lubatust rohkem; nende asetus ei ole vastavuses tüübikinnitusega.', 'VO,OV'),
        ('G:6.2.7', 'G:6.2', 'Juhtimisseadised', ''),
        ('6.2.7', 'G:6.2.7', 'Sõiduki ohutuks käitamiseks vajalik seadis ei tööta õigesti. Mõjutab ohutut käitamist.', 'OV,EOV'),
        ('G:6.2.8', 'G:6.2', 'Kabiini astmed', ''),
        ('6.2.8.a', 'G:6.2.8', 'Ebakindel aste või platvorm. Stabiilsus ei ole piisav.', 'VO,OV'),
        ('6.2.8.b', 'G:6.2.8', 'Astme või platvormi seisund võib kasutajatele vigastusi põhjustada.', 'OV'),
        ('G:6.2.9', 'G:6.2', 'Muud sõiduki sise- ja välisseadmed', ''),
        ('6.2.9.a', 'G:6.2.9', 'Muu seadme kinnitus on defektne.', 'OV'),
        ('6.2.9.b', 'G:6.2.9', 'Muu seade ei vasta nõuetele. Osad on paigaldatud nii, et võivad tekitada vigastusi; mõjutab ohutut käitamist.', 'VO,OV'),
        ('6.2.9.c', 'G:6.2.9', 'Hüdraulikaseade lekib. Ohtliku materjali ülemäärane kadu.', 'VO,OV'),
        ('G:6.2.10', 'G:6.2', 'Poritiivad, -plekid, -kummid, pritsmekaitsevarustus', ''),
        ('6.2.10.a', 'G:6.2.10', 'Komponent puudub, on lahti tulnud või tõsiselt korrodeerunud. Võib tekitada vigastusi; võib küljest ära kukkuda.', 'VO,OV'),
        ('6.2.10.b', 'G:6.2.10', 'Komponent on rehvile/rattale liiga lähedal (pritsmekaitse). Komponent on rehvile/rattale liiga lähedal (poritiivad).', 'VO,OV'),
        ('6.2.10.c', 'G:6.2.10', 'Ei vasta nõuetele. Turvis on liiga vähe kaetud.', 'VO,OV'),
        ('7', '', 'Muu varustus', ''),
        ('G:7.1', '7', 'Turvavööd / turvavöö pandlad ja turvasüsteemid', ''),
        ('G:7.1.1', 'G:7.1', 'Turvavööde / turvavööde pannalde kinnituste turvalisus', ''),
        ('7.1.1.a', 'G:7.1.1', 'Kinnituspunkt on oluliselt halvenenud seisundis. Mõjutab stabiilsust.', 'OV,EOV'),
        ('7.1.1.b', 'G:7.1.1', 'Kinnituspunkt on lahti tulnud.', 'OV'),
        ('G:7.1.2', 'G:7.1', 'Turvavööde / turvavööde pannalde seisund', ''),
        ('7.1.2.a', 'G:7.1.2', 'Kohustuslik turvavöö puudub või seda ei ole paigaldatud.', 'OV'),
        ('7.1.2.b', 'G:7.1.2', 'Turvavöö on kahjustunud. Mis tahes sisselõige või märk väljavenimisest.', 'VO,OV'),
        ('7.1.2.c', 'G:7.1.2', 'Turvavöö ei vasta nõuetele.', 'OV'),
        ('7.1.2.d', 'G:7.1.2', 'Turvavöö pannal on kahjustunud või ei toimi õigesti.', 'OV'),
        ('7.1.2.e', 'G:7.1.2', 'Turvavöö tõmbur on kahjustunud või ei toimi õigesti.', 'OV'),
        ('G:7.1.3', 'G:7.1', 'Turvavöö koormuse piiraja', ''),
        ('7.1.3.a', 'G:7.1.3', 'Koormuse piiraja puudub ilmselgelt või ei sobi asjaomasele sõidukile.', 'OV'),
        ('7.1.3.b', 'G:7.1.3', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('G:7.1.4', 'G:7.1', 'Turvavöö eelpingutid', ''),
        ('7.1.4.a', 'G:7.1.4', 'Eelpinguti puudub ilmselgelt või ei sobi asjaomasele sõidukile.', 'OV'),
        ('7.1.4.b', 'G:7.1.4', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('G:7.1.5', 'G:7.1', 'Turvapadjasüsteem', ''),
        ('7.1.5.a', 'G:7.1.5', 'Turvapadjasüsteem puudub ilmselgelt või ei sobi asjaomasele sõidukile.', 'OV'),
        ('7.1.5.b', 'G:7.1.5', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('7.1.5.c', 'G:7.1.5', 'Turvapadjasüsteem ilmselgelt ei tööta.', 'OV'),
        ('G:7.1.6', 'G:7.1', 'SRS-süsteemid', ''),
        ('7.1.6.a', 'G:7.1.6', 'SRS-süsteemi rikkeindikaator näitab süsteemis tõrget.', 'OV'),
        ('7.1.6.b', 'G:7.1.6', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('G:7.2', '7', 'Tulekustuti (X)', ''),
        ('7.2.a', 'G:7.2', 'Puudub.', 'OV'),
        ('7.2.b', 'G:7.2', 'Ei vasta nõuetele. Kui on nõutav (nt taksod, bussid jne).', 'VO,OV'),
        ('G:7.3', '7', 'Lukud ja kasutamistõkis', ''),
        ('7.3.a', 'G:7.3', 'Tõkis ei toimi – ei takista sõiduki käitamist.', 'VO'),
        ('7.3.b', 'G:7.3', 'Defektne. Soovimatu lukustumine või blokeerumine.', 'OV,EOV'),
        ('G:7.4', '7', 'Ohukolmnurk (kui see on nõutav) (X)', ''),
        ('7.4.a', 'G:7.4', 'Puudub või ei ole komplektne.', 'VO'),
        ('7.4.b', 'G:7.4', 'Ei vasta nõuetele.', 'VO'),
        ('G:7.5', '7', 'Esmaabivahendid (kui need on nõutavad) (X)', ''),
        ('7.5', 'G:7.5', 'Puuduvad, ei ole komplektsed või ei vasta nõuetele.', 'VO'),
        ('G:7.6', '7', 'Ratta tõkiskingad (-kiilud) (kui need on nõutavad) (X)', ''),
        ('7.6', 'G:7.6', 'Puuduvad või on halvas seisundis, ei ole piisavalt stabiilsed või piisava suurusega.', 'OV'),
        ('G:7.7', '7', 'Helisignaalseade', ''),
        ('7.7.a', 'G:7.7', 'Ei tööta korralikult. Ei tööta üldse.', 'VO,OV'),
        ('7.7.b', 'G:7.7', 'Ebakindel juhtseadis.', 'VO'),
        ('7.7.c', 'G:7.7', 'Ei vasta nõuetele. Heli võib ajada segi ametivõimude poolt kasutatavate sireenidega.', 'VO,OV'),
        ('G:7.8', '7', 'Kiirusmõõdik', ''),
        ('7.8.a', 'G:7.8', 'Ei ole paigaldatud vastavalt nõuetele. Puudub (kui on nõutav).', 'VO,OV'),
        ('7.8.b', 'G:7.8', 'Talitlus on häiritud. Ei toimi üldse.', 'VO,OV'),
        ('7.8.c', 'G:7.8', 'Mõõdik ei ole piisavalt valgustatud. Mõõdik ei ole valgustatud.', 'VO,OV'),
        ('G:7.9', '7', 'Sõidumeerik (kui see on paigaldatud/nõutav)', ''),
        ('7.9.a', 'G:7.9', 'Ei ole paigaldatud vastavalt nõuetele.', 'OV'),
        ('7.9.b', 'G:7.9', 'Ei tööta.', 'OV'),
        ('7.9.c', 'G:7.9', 'Defektsed või puuduvad plommid.', 'OV'),
        ('7.9.d', 'G:7.9', 'Paigaldustahvel puudub, on loetamatu või aegunud.', 'OV'),
        ('7.9.e', 'G:7.9', 'Ilmne rikkumine või manipuleerimine.', 'OV'),
        ('7.9.f', 'G:7.9', 'Rehvide suurus ei vasta kalibreerimisparameetritele.', 'OV'),
        ('G:7.10', '7', 'Kiiruspiirik (kui see on paigaldatud/nõutav) (+E)', ''),
        ('7.10.a', 'G:7.10', 'Ei ole paigaldatud vastavalt nõuetele.', 'OV'),
        ('7.10.b', 'G:7.10', 'Ei ole ilmselgelt töökorras.', 'OV'),
        ('7.10.c', 'G:7.10', 'Vale määratud kiirus (kui seda on kontrollitud).', 'OV'),
        ('7.10.d', 'G:7.10', 'Defektsed või puuduvad plommid.', 'OV'),
        ('7.10.e', 'G:7.10', 'Plaat puudub või on loetamatu.', 'OV'),
        ('7.10.f', 'G:7.10', 'Rehvide suurus ei vasta kalibreerimisparameetritele.', 'OV'),
        ('G:7.11', '7', 'Läbisõidumõõdik, kui see on olemas (X)', ''),
        ('7.11.a', 'G:7.11', 'Ilmselgelt manipuleeritud (pettus), et vähendada sõiduki läbisõidunäitu või näidata seda tegelikust erinevana.', 'OV'),
        ('7.11.b', 'G:7.11', 'Ilmselgelt ei tööta.', 'OV'),
        ('G:7.12', '7', 'Elektrooniline stabiilsuskontroll (ESC), kui see on paigaldatud/nõutav (X)', ''),
        ('7.12.a', 'G:7.12', 'Ratta kiirusandurid puuduvad või on kahjustunud.', 'OV'),
        ('7.12.b', 'G:7.12', 'Juhtmestik on kahjustunud.', 'OV'),
        ('7.12.c', 'G:7.12', 'Muud osad puuduvad või on kahjustunud.', 'OV'),
        ('7.12.d', 'G:7.12', 'Lüliti on kahjustunud või ei tööta õigesti.', 'OV'),
        ('7.12.e', 'G:7.12', 'ESC-süsteemi rikkeindikaator näitab süsteemis tõrget.', 'OV'),
        ('7.12.f', 'G:7.12', 'Süsteem näitab tõrget sõiduki elektroonilise liidese kaudu.', 'OV'),
        ('8', '', 'Saaste', ''),
        ('G:8.1', '8', 'Müra', ''),
        ('G:8.1.1', 'G:8.1', 'Müravähendussüsteem (+E)', ''),
        ('8.1.1.a', 'G:8.1.1', 'Müratasemed ületavad nõuetes lubatavaid tasemeid.', 'OV'),
        ('8.1.1.b', 'G:8.1.1', 'Müravähendussüsteemi mingi osa on lahti tulnud, kahjustunud, valesti paigaldatud, puudub või seda on ilmselt muudetud, nii et see mõjub negatiivselt müratasemele. Väga tõsine küljest äratuleku oht.', 'OV,EOV'),
        ('G:8.2', '8', 'Heitgaasid', ''),
        ('G:8.2.1', 'G:8.2', 'Ottomootori tekitatav heide', ''),
        ('G:8.2.1.1', 'G:8.2.1', 'Heitgaaside kontrolli seadmed', ''),
        ('8.2.1.1.a', 'G:8.2.1.1', 'Tootja paigaldatud heitekontrolliseadmed puuduvad, neid on muudetud või need on ilmselt vigased.', 'OV'),
        ('8.2.1.1.b', 'G:8.2.1.1', 'Heitkoguste mõõtmist mõjutavad lekked.', 'OV'),
        ('8.2.1.1.c', 'G:8.2.1.1', 'Rikkeindikaator ei näita nõuetekohast toimimist.', 'OV'),
        ('G:8.2.1.2', 'G:8.2.1', 'Gaasiline heide (E)', ''),
        ('8.2.1.2.a', 'G:8.2.1.2', 'Gaasilised heited ületavad tootja kindlaks määratud konkreetseid tasemeid.', 'OV'),
        ('8.2.1.2.b', 'G:8.2.1.2', 'Või juhul, kui see teave ei ole kättesaadav, süsinikmonooksiidi heited ületavad: i) sõidukite puhul, mille heitgaase ei kontrollita spetsiaalse heitekontrollisüsteemi abil, — 4,5 % või — 3,5 % vastavalt nõuetes kindlaks määratud esmase registreerimise või kasutuselevõtu kuupäevale; ii) sõidukite puhul, mille heitgaase kontrollitakse sellise süsteemi abil, — tühikäigul 0,5 % — kõrgendatud pööretel 0,3 % või — tühikäigul 0,3 % — kõrgendatud pööretel 0,2 % vastavalt samale kuupäevale.', 'OV'),
        ('8.2.1.2.c', 'G:8.2.1.2', 'Lambda väärtus ei jää vahemikku 1 ± 0,03 või ei ole kooskõlas tootja spetsifikatsiooniga.', 'OV'),
        ('8.2.1.2.d', 'G:8.2.1.2', 'Pardadiagnostika näit osutab olulisele rikkele.', 'OV'),
        ('8.2.1.2.e', 'G:8.2.1.2', 'Kaugmõõtmine näitab olulist nõuetele mittevastavust.', 'OV'),
        ('G:8.2.2', 'G:8.2', 'Diiselmootori tekitatav heide', ''),
        ('G:8.2.2.1', 'G:8.2.2', 'Heitgaaside kontrolli seadmed', ''),
        ('8.2.2.1.a', 'G:8.2.2.1', 'Tootja paigaldatud heitekontrolliseadmed puuduvad või need on ilmselgelt vigased.', 'OV'),
        ('8.2.2.1.b', 'G:8.2.2.1', 'Heitkoguste mõõtmist mõjutavad lekked.', 'OV'),
        ('8.2.2.1.c', 'G:8.2.2.1', 'Rikkeindikaator ei näita nõuetekohast toimimist.', 'OV'),
        ('8.2.2.1.d', 'G:8.2.2.1', 'Ebapiisav kogus reagenti (kui see on vajalik).', 'OV'),
        ('G:8.2.2.2', 'G:8.2.2', 'Suitsusus. Seda nõuet ei kohaldata enne 1. jaanuari 1980 registreeritud või kasutusele võetud sõidukite suhtes.', ''),
        ('8.2.2.2.a', 'G:8.2.2.2', 'Sõidukite puhul, mis on registreeritud või esmakordselt kasutusele võetud pärast nõuetes kindlaks määratud kuupäeva, ületab suitsusus taset, mis on märgitud sõidukile kinnitatud tootja andmesildil.', 'OV'),
        ('8.2.2.2.b', 'G:8.2.2.2', 'Kui see teave ei ole kättesaadav või kui nõuete alusel ei ole kontrollväärtuste kasutamine lubatud, siis — ülelaadeta mootorite puhul 2,5 m⁻¹, — turbomootorite puhul 3,0 m⁻¹, või nõuetes määratud või pärast nõuetes kindlaks määratud kuupäeva esmaselt registreeritud või kasutusele võetud sõidukite puhul 1,5 m⁻¹ või 0,7 m⁻¹', 'OV'),
        ('8.2.2.2.c', 'G:8.2.2.2', 'Kaugmõõtmine näitab olulist nõuetele mittevastavust.', 'OV'),
        ('G:8.4', '8', 'Muud keskkonnaga seotud punktid', ''),
        ('G:8.4.1', 'G:8.4', 'Vedelikulekked', ''),
        ('8.4.1', 'G:8.4.1', 'Mis tahes ülemäärane vedelikuleke (muu kui vesi), mis võib kahjustada keskkonda või kujutada ohtu teistele liiklejatele. Pidev tilkade teke, mis kujutab endast väga tõsist ohtu.', 'OV,EOV'),
        ('9', '', 'Täiendavad ülevaatused reisijateveoks kasutatavatele M2- ja M3-kategooria sõidukitele', ''),
        ('G:9.1', '9', 'Uksed', ''),
        ('G:9.1.1', 'G:9.1', 'Sisse- ja väljapääsud', ''),
        ('9.1.1.a', 'G:9.1.1', 'Defektne toimimine.', 'OV'),
        ('9.1.1.b', 'G:9.1.1', 'Halvenenud seisund. Võib tekitada vigastusi.', 'VO,OV'),
        ('9.1.1.c', 'G:9.1.1', 'Avariiolukordadeks ette nähtud juhtimisseade on defektne.', 'OV'),
        ('9.1.1.d', 'G:9.1.1', 'Uste kaugjuhtimisseadmed või hoiatusseadised on defektsed.', 'OV'),
        ('G:9.1.2', 'G:9.1', 'Avariiväljapääsud', ''),
        ('9.1.2.a', 'G:9.1.2', 'Defektne toimimine.', 'OV'),
        ('9.1.2.b', 'G:9.1.2', 'Avariiväljapääsu tähistavad sildid on loetamatud. Avariiväljapääsu tähistavad sildid puuduvad.', 'VO,OV'),
        ('9.1.2.c', 'G:9.1.2', 'Puudub klaasipurustushaamer.', 'VO'),
        ('9.1.2.d', 'G:9.1.2', 'Juurdepääs on blokeeritud.', 'OV'),
        ('G:9.2', '9', 'Niiskuse ja jäite eemaldamise süsteem (X)', ''),
        ('9.2.a', 'G:9.2', 'Ei tööta õigesti. Mõjutab sõiduki ohutut käitamist.', 'VO,OV'),
        ('9.2.b', 'G:9.2', 'Mürgiste gaaside või heitgaaside pääsemine juhikabiini või sõitjateruumi. Oht sõidukis viibivate isikute tervisele.', 'OV,EOV'),
        ('9.2.c', 'G:9.2', 'Defektne jäite eemaldamise süsteem (kui see on kohustuslik).', 'OV'),
        ('G:9.3', '9', 'Ventileerimis- ja küttesüsteem (X)', ''),
        ('9.3.a', 'G:9.3', 'Defektne toimimine. Oht sõidukis viibivate isikute tervisele.', 'VO,OV'),
        ('9.3.b', 'G:9.3', 'Mürgiste gaaside või heitgaaside pääsemine juhikabiini või sõitjateruumi. Oht sõidukis viibivate isikute tervisele.', 'OV,EOV'),
        ('G:9.4', '9', 'Istmed', ''),
        ('G:9.4.1', 'G:9.4', 'Sõitjakohad (sh reisisaatjate istmed ja lapse turvasüsteemid, kui need on olemas)', ''),
        ('9.4.1', 'G:9.4.1', 'Klappistmed (kui need on lubatud) ei tööta automaatselt. Need blokeerivad avariiväljapääsu.', 'VO,OV'),
        ('G:9.4.2', 'G:9.4', 'Juhiiste (lisanõuded)', ''),
        ('9.4.2.a', 'G:9.4.2', 'Defektne erivarustus, näiteks pimestamisvastane vari. Vaateväli on ahenenud.', 'VO,OV'),
        ('9.4.2.b', 'G:9.4.2', 'Juhi kaitseseadised on ebakindlad. Võivad tekitada vigastusi.', 'VO,OV'),
        ('G:9.5', '9', 'Sisevalgustus ja liiniinfo seadmed (X)', ''),
        ('9.5', 'G:9.5', 'Seade on defektne. Ei toimi üldse.', 'VO,OV'),
        ('G:9.6', '9', 'Vahekäigud, seisukohad', ''),
        ('9.6.a', 'G:9.6', 'Ebakindel põrand. Mõjutab stabiilsust.', 'OV,EOV'),
        ('9.6.b', 'G:9.6', 'Defektsed käsipuud või käepidemed. Ebakindlad või kasutuskõlbmatud.', 'VO,OV'),
        ('G:9.7', '9', 'Trepid ja astmed', ''),
        ('9.7.a', 'G:9.7', 'Halvenenud seisund. Kahjustatud seisund. Mõjutab stabiilsust.', 'VO,OV,EOV'),
        ('9.7.b', 'G:9.7', 'Sissetõmmatavad astmed ei toimi õigesti.', 'OV'),
        ('G:9.8', '9', 'Reisijatega suhtlemise süsteem (X)', ''),
        ('9.8', 'G:9.8', 'Süsteem on defektne. Ei toimi üldse.', 'VO,OV'),
        ('G:9.9', '9', 'Kirjalik teave (X)', ''),
        ('9.9', 'G:9.9', 'Teave puudub, on väär või loetamatu. Eksitav teave.', 'VO,OV'),
        ('G:9.10', '9', 'Laste vedu käsitlevad nõuded (X)', ''),
        ('G:9.10.1', 'G:9.10', 'Uksed', ''),
        ('9.10.1', 'G:9.10.1', 'Uksed ei ole kaitstud kooskõlas asjaomast transpordiliiki käsitlevate nõuetega', 'OV'),
        ('G:9.10.2', 'G:9.10', 'Signaal- ja eriseadmed', ''),
        ('9.10.2', 'G:9.10.2', 'Signaal- või eriseadmed puuduvad.', 'VO'),
        ('G:9.11', '9', 'Piiratud liikumisvõimega isikute vedu käsitlevad nõuded (X)', ''),
        ('G:9.11.1', 'G:9.11', 'Uksed, rambid ja tõstukid', ''),
        ('9.11.1.a', 'G:9.11.1', 'Defektne toimimine. Mõjutab ohutut käitamist.', 'VO,OV'),
        ('9.11.1.b', 'G:9.11.1', 'Halvenenud seisund. Mõjutab stabiilsust, võib tekitada vigastusi.', 'VO,OV'),
        ('9.11.1.c', 'G:9.11.1', 'Defektne juhtseadis (defektsed juhtseadised). Mõjutab ohutut käitamist.', 'VO,OV'),
        ('9.11.1.d', 'G:9.11.1', 'Defektne hoiatusseadis (defektsed hoiatusseadised). Ei toimi üldse.', 'VO,OV'),
        ('G:9.11.2', 'G:9.11', 'Ratastooli kinnitamise süsteem', ''),
        ('9.11.2.a', 'G:9.11.2', 'Defektne toimimine. Mõjutab ohutut käitamist.', 'VO,OV'),
        ('9.11.2.b', 'G:9.11.2', 'Halvenenud seisund. Mõjutab stabiilsust, võib tekitada vigastusi.', 'VO,OV'),
        ('9.11.2.c', 'G:9.11.2', 'Defektne juhtseadis (defektsed juhtseadised). Mõjutab ohutut käitamist.', 'VO,OV'),
        ('G:9.11.3', 'G:9.11', 'Signaal- ja eriseadmed', ''),
        ('9.11.3', 'G:9.11.3', 'Signaal- või eriseadmed puuduvad.', 'OV'),
        ('10', '', 'Sõiduki sobivus', ''),
        ('G:10.1', '10', 'Esisein (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.1.1', 'G:10.1', 'Rooste või deformatsiooni tõttu kahjustada saanud detailid. Pragunenud detail, mis seab ohtu veoseruumi terviklikkuse.', 'OV,EOV'),
        ('10.1.2', 'G:10.1', 'Ebapiisav tugevus (tunnistus või märgis, kui see on olemas). Veetava veose jaoks ebapiisav kõrgus.', 'OV,EOV'),
        ('G:10.2', '10', 'Külgseinad (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.2.1', 'G:10.2', 'Rooste või deformatsiooni tõttu kahjustada saanud detailid, hingede või lukkude seisukord ei ole nõuetekohane. Pragunenud osa; hinged või lukud puuduvad või ei tööta.', 'OV,EOV'),
        ('10.2.2', 'G:10.2', 'Tugi ei ole piisavalt tugev (tunnistus või märgis, kui on olemas). Veetava veose jaoks ebapiisav kõrgus.', 'OV,EOV'),
        ('10.2.3', 'G:10.2', 'Puidust külgpaneelide seisukord ei ole nõuetekohane. Pragunenud detail.', 'OV,EOV'),
        ('G:10.3', '10', 'Tagasein (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.3.1', 'G:10.3', 'Rooste või deformatsiooni tõttu kahjustada saanud detailid, hingede või lukkude seisukord ei ole nõuetekohane. Pragunenud osa; hinged või lukud puuduvad või ei tööta.', 'OV,EOV'),
        ('10.3.2', 'G:10.3', 'Ebapiisav tugevus (tunnistus või märgis, kui see on olemas). Veetava veose jaoks ebapiisav kõrgus.', 'OV,EOV'),
        ('G:10.4', '10', 'Vertikaaltoed (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.4.1', 'G:10.4', 'Rooste või deformatsiooni tõttu kahjustada saanud detailid või need ei ole nõuetekohaselt sõidukile kinnitatud. Pragunenud osa; kinnitus sõiduki külge ei ole stabiilne.', 'OV,EOV'),
        ('10.4.2', 'G:10.4', 'Tugevus või konstruktsioon ei ole nõuetekohane. Veetava veose jaoks ebapiisav kõrgus.', 'OV,EOV'),
        ('G:10.5', '10', 'Sidumisvahendite kinnituskohad (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.5.1', 'G:10.5', 'Seisukord või konstruktsioon ei ole nõuetekohane. Ei pea vastu sidemele mõjuvale ettenähtud jõule.', 'OV,EOV'),
        ('10.5.2', 'G:10.5', 'Arv ei ole piisav. Arv ei ole piisav, et pidada vastu sidemele mõjuvale ettenähtud jõule.', 'OV,EOV'),
        ('G:10.6', '10', 'Nõutavad erikonstruktsioonid (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.6.1', 'G:10.6', 'Seisukord ei ole nõuetekohane, on kahjustatud. Pragunenud osa; ei pea kinnitusjõule vastu.', 'OV,EOV'),
        ('10.6.2', 'G:10.6', 'Ei sobi asjaomase veose vedamiseks. Puuduvad.', 'OV,EOV'),
        ('G:10.7', '10', 'Põhi (kui kasutatakse veose kinnitamiseks)', ''),
        ('10.7.1', 'G:10.7', 'Seisukord ei ole nõuetekohane, on kahjustatud. Pragunenud osa; ei pea veosele vastu.', 'OV,EOV'),
        ('10.7.2', 'G:10.7', 'Ebapiisav kandevõime. Ei pea veosele vastu.', 'OV,EOV'),
        ('20', '', 'Kinnitusmeetodid', ''),
        ('G:20.1', '20', 'Lukustamine, tõkestamine ja otsene kinnitus', ''),
        ('G:20.1.1', 'G:20.1', 'Veose otsene kinnitamine (tõkestamine)', ''),
        ('20.1.1.1', 'G:20.1.1', 'Edasisuunaline kaugus esiseinani liiga suur, kui seina kasutatakse veose otseseks kinnitamiseks. Üle 15 cm ja esineb seina läbistamise oht.', 'OV,EOV'),
        ('20.1.1.2', 'G:20.1.1', 'Külgsuunaline kaugus külgseinani liiga suur, kui seina kasutatakse veose otseseks kinnitamiseks. Üle 15 cm ja esineb seina läbistamise oht.', 'OV,EOV'),
        ('20.1.1.3', 'G:20.1.1', 'Tagasisuunaline kaugus tagaseinani liiga suur, kui seina kasutatakse veose otseseks kinnitamiseks. Üle 15 cm ja esineb seina läbistamise oht.', 'OV,EOV'),
        ('G:20.1.2', 'G:20.1', 'Kinnitusvahendid (nt tõkked, talad, latid ja kiilud ees, külgedel ja taga)', ''),
        ('20.1.2.1', 'G:20.1.2', 'Ei ole sõiduki külge nõuetekohaselt kinnitatud. Ebapiisav kinnitus. Ei pea kinnitusjõule vastu, on lahti.', 'VO,OV,EOV'),
        ('20.1.2.2', 'G:20.1.2', 'Kinnitus ei ole nõuetekohane. Ebapiisav kinnitus. Täiesti mõjutu.', 'VO,OV,EOV'),
        ('20.1.2.3', 'G:20.1.2', 'Kinnitusvahendid ei ole piisavalt sobivad. Kinnitusvahendid on täiesti ebasobivad.', 'OV,EOV'),
        ('20.1.2.4', 'G:20.1.2', 'Pakendite kinnitamiseks valitud meetod ei ole optimaalne. Valitud meetod on täiesti sobimatu.', 'OV,EOV'),
        ('G:20.1.3', 'G:20.1', 'Otsene kinnitamine võrkude ja katetega', ''),
        ('20.1.3.1', 'G:20.1.3', 'Võrkude ja katete seisukord (märgis puudub / on kahjustatud, kuid muidu heas seisukorras). Veose kinnitusvahendid on kahjustatud. Veose kinnitusvahendid on olulisel määral kahjustatud ja ei ole enam kasutuskõlblikud.', 'VO,OV,EOV'),
        ('20.1.3.2', 'G:20.1.3', 'Võrgud ja katted ei ole piisavalt tugevad. Suudavad vastu seista nõutavale kinnitusjõule vähem kui 2/3 ulatuses.', 'OV,EOV'),
        ('20.1.3.3', 'G:20.1.3', 'Võrgud ja katted ei ole piisavalt kinnitatud. Kinnitused suudavad vastu seista nõutavale kinnitusjõule vähem kui 2/3 ulatuses.', 'OV,EOV'),
        ('20.1.3.4', 'G:20.1.3', 'Võrgud ja katted ei ole piisavalt sobivad veose kinnitamiseks. Täiesti sobimatud.', 'OV,EOV'),
        ('G:20.1.4', 'G:20.1', 'Laadungiüksuste või tühiruumide eraldamine ja polsterdus', ''),
        ('20.1.4.1', 'G:20.1.4', 'Eralduse ja polsterduse sobivus. Eraldus- või tühiruum on liiga suur.', 'OV,EOV'),
        ('G:20.1.5', 'G:20.1', 'Otsene kinnitus (horisontaal-, põiki-, diagonaal-, silmus- ja elastne kinnitus)', ''),
        ('20.1.5.1', 'G:20.1.5', 'Nõutav kinnitusjõud ei ole piisav. On alla 2/3 nõutavast jõust.', 'OV,EOV'),
        ('G:20.2', '20', 'Hõõrdlukk', ''),
        ('G:20.2.1', 'G:20.2', 'Nõutava kinnitusjõu järgimine', ''),
        ('20.2.1.1', 'G:20.2.1', 'Nõutav kinnitusjõud ei ole piisav. On alla 2/3 nõutavast jõust.', 'OV,EOV'),
        ('G:20.3', '20', 'Veose kinnitusvahendid', ''),
        ('20.3.1', 'G:20.3', 'Veose kinnitusvahendite sobivus. Täiesti ebasobivad.', 'OV,EOV'),
        ('20.3.2', 'G:20.3', 'Märgis (nt partii/katsehaagis) puudub / on kahjustatud, kuid vahend on heas seisukorras. Märgis (nt partii/katsehaagis) puudub / on kahjustatud, kuid vahendi seisukord on märgatavalt halvenenud.', 'VO,OV'),
        ('20.3.3', 'G:20.3', 'Veose kinnitusvahendid on kahjustatud. Veose kinnitusvahendid on olulisel määral kahjustatud ega ole enam kasutuskõlblikud.', 'OV,EOV'),
        ('20.3.4', 'G:20.3', 'Vintse on valesti kasutatud. Vintsid on defektsed.', 'OV,EOV'),
        ('20.3.5', 'G:20.3', 'Veos on valesti kinnitatud (nt puudub servakaitse). Veose kinnitusvahendid on defektsed (nt sõlmed).', 'OV,EOV'),
        ('20.3.6', 'G:20.3', 'Veose kinnitusvahendid ei ole nõuetekohaselt kinnitatud. On alla 2/3 nõutavast jõust.', 'OV,EOV'),
        ('G:20.4', '20', 'Lisavarustus (nt hõõrdematid, servakaitsed, servajalased)', ''),
        ('20.4.1', 'G:20.4', 'Kasutatud on ebastabiilseid vahendeid. Kasutatud on valesid või defektseid vahendeid. Kasutatud vahendid on täiesti sobimatud.', 'VO,OV,EOV'),
        ('G:20.5', '20', 'Puistematerjali, kerge ja lahtise materjali vedu', ''),
        ('20.5.1', 'G:20.5', 'Puistematerjal lendub veo käigus teele, võib häirida liiklust. Ohustab liiklust.', 'OV,EOV'),
        ('20.5.2', 'G:20.5', 'Puistematerjal ei ole nõuetekohaselt kinnitatud. Veose kadu, mis ohustab liiklust.', 'OV,EOV'),
        ('20.5.3', 'G:20.5', 'Katte puudumine kergete kaupade puhul. Veose kadu, mis ohustab liiklust.', 'OV,EOV'),
        ('G:20.6', '20', 'Ümarpuidu vedu', ''),
        ('20.6.1', 'G:20.6', 'Veetav materjal on osaliselt lahtine (palgid)', 'EOV'),
        ('20.6.2', 'G:20.6', 'Laadungiüksuse kinnitamisjõud ei ole piisav. On alla 2/3 nõutavast jõust.', 'OV,EOV'),
        ('30', '20', 'Veos on täielikult kinnitamata', 'EOV')
        ) AS t(code, parent_code, name, severities);

        INSERT INTO classifier.classifier_value (
            classifier_value_key, classifier_key, code, name, description,
            parent_key, valid_from, created_by
        )
        SELECT r.value_key, v_key, r.code, r.name, NULLIF(r.severities, ''),
               p.value_key, CURRENT_DATE, 'system'
        FROM tmp_rsi_failed_reason r
        LEFT JOIN tmp_rsi_failed_reason p ON p.code = r.parent_code;

        IF EXISTS (
            SELECT 1 FROM tmp_rsi_failed_reason r
            WHERE r.parent_code <> ''
              AND NOT EXISTS (SELECT 1 FROM tmp_rsi_failed_reason p WHERE p.code = r.parent_code)
        ) THEN
            RAISE EXCEPTION 'RSI_FAILED_REASON: unknown parent code';
        END IF;

        DROP TABLE tmp_rsi_failed_reason;
    END IF;
END $$;

COMMENT ON COLUMN erru.rsi_message.checked_items IS 'Väljaminev: [{"partCode","status":"not_checked"|"checked"|"non_compliant","defects":[{"defectCode","severity":"VO"|"OV"|"EOV"}],"nationalDefects":[...]}] — partCode = RSI_FAILED_REASON 1. tase (ERRU rsiItemType 0..10, 20), defectCode = RSI_FAILED_REASON leht (ERRU rsiFailedReason). nationalDefects = kontrollkaardilt eeltäidetud riiklikud TECHNICAL_CHECK rikked (ainult vihje, ei saadeta). Teisendatakse ERRU rsiCheckedItemType kujule saatmisel (POST/v1/erru/rsi/send.yml). Enne 20261125100000 saadetud teadetes võib olla vana TECHNICAL_CHECK-kuju (partCode CAA_*). Sissetulev: ERRU kuju nagu saabus.';

-- Saatmata RSI mustandid vanas TECHNICAL_CHECK-kujus (vt päis).
DELETE FROM erru.rsi_message m
WHERE m.direction = 'outgoing'
  AND NOT EXISTS (
      SELECT 1 FROM erru.rsi_message o
      WHERE o.rsi_message_key = m.rsi_message_key AND o.status <> 'initiated'
  );
