-- liquibase formatted sql
-- changeset ljvis:20260812100000 ignore:true
-- Schema erru already exists (created by 20260801100000-initial-erru-ctud.sql).
CREATE SCHEMA IF NOT EXISTS erru;

CREATE SEQUENCE IF NOT EXISTS erru.seq_cgr_request_key START 1;
CREATE SEQUENCE IF NOT EXISTS erru.seq_cgr_business_case_no START 1;

COMMENT ON SEQUENCE erru.seq_cgr_request_key IS 'Allocates the stable logical identity (cgr_request_key) of a CGR request. Consumed once per request, by both directions.';
COMMENT ON SEQUENCE erru.seq_cgr_business_case_no IS 'Allocates the running number of the human-readable business_case_id (CGR-EE-AAAA-NNNNN) for OUTGOING requests only. Inbound requests carry the sender''s own identifier and do not consume this sequence.';

-- cgr_request (INSERT-only snapshot — one row per request state)
CREATE TABLE erru.cgr_request (
    -- ── Identity & lifecycle ────────────────────────────────
    id                              BIGSERIAL       NOT NULL,
    cgr_request_key                 BIGINT          NOT NULL,
    version                         INTEGER         NOT NULL DEFAULT 1,
    direction                       VARCHAR(10)     NOT NULL,
    status                          VARCHAR(20)     NOT NULL,
    -- ── ERRU message envelope (globalHeaderType) ────────────
    business_case_id                VARCHAR(36)     NOT NULL,
    technical_id                    UUID,
    workflow_id                     UUID,
    sent_at                         TIMESTAMPTZ,
    cgr_from                        CHAR(2),
    cgr_to                          VARCHAR(2),
    -- ── Request body (globalBodyRequestType) ────────────────
    originating_authority           VARCHAR(50),
    request_source                  VARCHAR(30),
    request_purpose                 VARCHAR(30),
    -- ── Searched transport manager — name (7A, choice) ──────
    tm_first_name                   VARCHAR(100),
    tm_family_name                  VARCHAR(100),
    tm_date_of_birth                DATE,
    tm_place_of_birth               VARCHAR(200),
    tm_first_name_search_key        VARCHAR(20),
    tm_family_name_search_key       VARCHAR(20),
    -- ── Searched transport manager — certificate (7B, choice) ──
    certificate_number              VARCHAR(100),
    certificate_issue_date           DATE,
    certificate_issue_country        CHAR(2),
    -- ── Response — one entry per member state ───────────────
    member_states                   JSONB,
    -- ── Handling & errors ───────────────────────────────────
    handler_personal_code           VARCHAR(20),
    handler_name                    VARCHAR(200),
    error_message                   TEXT,
    -- ── Audit ───────────────────────────────────────────────
    created_at                      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    created_by                      VARCHAR(100)    NOT NULL DEFAULT 'system',
    CONSTRAINT pk_cgr_request PRIMARY KEY (id)
);

COMMENT ON TABLE  erru.cgr_request IS 'INSERT-only snapshot of an ERRU CGR (Check Good Repute / Mainepäring) request. Serves BOTH directions, distinguished by the direction column. Every state change appends a complete new row carrying the unchanged fields forward. Current state = DISTINCT ON (cgr_request_key) ORDER BY cgr_request_key, created_at DESC. UPDATE and DELETE on this table are forbidden. CGR is a synchronous request/response, possibly broadcast to all member states (cgr_to = ZZ): there is no separate "responded" status — the outgoing terminal state "sent" already carries the member_states document, written in the same call as the send.';
COMMENT ON COLUMN erru.cgr_request.id IS 'Per-row physical primary key.';
COMMENT ON COLUMN erru.cgr_request.cgr_request_key IS 'Stable logical identity of the request (from erru.seq_cgr_request_key). All snapshot rows of one request share this value. NOT unique. A "Kopeeri päring" action allocates a brand-new key — it never reuses the source request''s key.';
COMMENT ON COLUMN erru.cgr_request.version IS 'Snapshot ordinal. Starts at 1; incremented by 1 on every appended snapshot.';
COMMENT ON COLUMN erru.cgr_request.direction IS 'outgoing = Estonia asks other member state(s); incoming = another member state asks Estonia. Immutable across all snapshots of one request; determines which status chain applies.';
COMMENT ON COLUMN erru.cgr_request.status IS 'Lifecycle status. Outgoing: initiated -> sent. Incoming: received -> answered. Shared: error. sent is the outgoing terminal state: the synchronous member_states response is written in the same append as the send, there is no separate responded status. Allowed transitions enforced in DSL/Resql/ljvis/POST/erru/cgr/append-transition.sql. Estonian display labels live in the CGR_REQUEST_STATUS classifier, never in this column.';
COMMENT ON COLUMN erru.cgr_request.business_case_id IS 'ERRU business case identifier, max 36 chars. Outgoing: generated by us as CGR-EE-AAAA-NNNNN. Incoming: stored verbatim as received.';
COMMENT ON COLUMN erru.cgr_request.technical_id IS 'globalHeaderType/@technicalId. Used for inbound idempotency via uq_cgr_inbound_technical_id.';
COMMENT ON COLUMN erru.cgr_request.workflow_id IS 'globalHeaderType/@workflowId. Correlation key between a request and its response.';
COMMENT ON COLUMN erru.cgr_request.sent_at IS 'globalHeaderType/@sentAt. Empty on an unsent outgoing draft.';
COMMENT ON COLUMN erru.cgr_request.cgr_from IS 'globalHeaderType/@from (ISO 3166-1 alpha-2). Always EE for outgoing. Displayed via the COUNTRY classifier.';
COMMENT ON COLUMN erru.cgr_request.cgr_to IS 'globalHeaderType/@to. Either a single member state (ISO 3166-1 alpha-2) or the broadcast marker ZZ meaning "all member states". NULL only on an unsent draft where the field has not yet been resolved (append-draft.sql defaults an empty selection to ZZ immediately, so in practice this is never left NULL on a saved outgoing draft).';
COMMENT ON COLUMN erru.cgr_request.originating_authority IS 'globalBodyRequestType/@originatingAuthority. Value from the COMPETENT_AUTHORITY classifier (shared with CTUD).';
COMMENT ON COLUMN erru.cgr_request.request_source IS 'globalSourcePurposeGroup/@requestSource. Value from the CGR_REQUEST_SOURCE classifier.';
COMMENT ON COLUMN erru.cgr_request.request_purpose IS 'globalSourcePurposeGroup/@requestPurpose. Value from the CGR_REQUEST_PURPOSE classifier. Heartbeat requests are never persisted (see append-cgr-inbound.sql) — this column never actually holds Heartbeat on a stored row, but the classifier still lists it for completeness/documentation.';
COMMENT ON COLUMN erru.cgr_request.tm_first_name IS 'Searched transport manager first name (7A block). XSD choice: this block or the certificate block (7B) must be complete — see chk_cgr_search_choice.';
COMMENT ON COLUMN erru.cgr_request.tm_family_name IS 'Searched transport manager family name (7A block).';
COMMENT ON COLUMN erru.cgr_request.tm_date_of_birth IS 'Searched transport manager date of birth (7A block). Primary search key together with the name.';
COMMENT ON COLUMN erru.cgr_request.tm_place_of_birth IS 'Searched transport manager place of birth (7A block). Optional even when the name block is used.';
COMMENT ON COLUMN erru.cgr_request.tm_first_name_search_key IS 'NYSIIS phonetic key of tm_first_name, computed server-side via TEMPLATES/erru/cgr/nysiis-key.yml before the outgoing message is sent. Never entered by the user. NULL for incoming requests until re-derived if needed.';
COMMENT ON COLUMN erru.cgr_request.tm_family_name_search_key IS 'NYSIIS phonetic key of tm_family_name. See tm_first_name_search_key.';
COMMENT ON COLUMN erru.cgr_request.certificate_number IS 'Searched CPC certificate number (7B block). XSD choice: this block or the name block (7A) must be complete.';
COMMENT ON COLUMN erru.cgr_request.certificate_issue_date IS 'CPC certificate issue date (7B block).';
COMMENT ON COLUMN erru.cgr_request.certificate_issue_country IS 'CPC certificate issuing country (7B block). Displayed via the COUNTRY classifier.';
COMMENT ON COLUMN erru.cgr_request.member_states IS 'One entry per responding member state. JSONB rather than child tables because the data arrives from an external system and is never edited. Shape per entry: {"memberStateCode","statusCode","statusMessage","transportManagerDetails":{"respondingAuthority","searchMethod","nameDetails":{...},"addressDetails":{...},"certificateDetails":{"certificateNumber","certificateIssueDate","certificateIssueCountry","certificateValidity","fitness":{"fitnessStatus","unfitStartDate","unfitEndDate"}},"transportUndertakings":{"totalManagedUndertakings","totalManagedVehicles","undertaking":[{"transportUndertakingName","communityLicenceNumber","communityLicenceStatus","numberOfVehicles","address":{...}}]}}}. transportManagerDetails is present only when statusCode = Found. NULL until the first response is recorded.';
COMMENT ON COLUMN erru.cgr_request.handler_personal_code IS 'Personal code (isikukood) of the official handling the request. Empty for platform-generated / inbound-served requests.';
COMMENT ON COLUMN erru.cgr_request.handler_name IS 'Display name of the handling official.';
COMMENT ON COLUMN erru.cgr_request.error_message IS 'Diagnostic text for status = error.';
COMMENT ON COLUMN erru.cgr_request.created_at IS 'Snapshot creation timestamp; ordering key for latest-row resolution.';
COMMENT ON COLUMN erru.cgr_request.created_by IS 'Personal code (isikukood) of the actor, or a system identifier string for automated transitions.';

CREATE INDEX idx_cgr_key_ts                ON erru.cgr_request (cgr_request_key, created_at DESC);
CREATE INDEX idx_cgr_business_case_id      ON erru.cgr_request (business_case_id);
CREATE INDEX idx_cgr_status                ON erru.cgr_request (status);
CREATE INDEX idx_cgr_direction             ON erru.cgr_request (direction);
CREATE INDEX idx_cgr_technical_id          ON erru.cgr_request (technical_id);
CREATE INDEX idx_cgr_workflow_id           ON erru.cgr_request (workflow_id);
CREATE INDEX idx_cgr_sent_at               ON erru.cgr_request (sent_at DESC);
CREATE INDEX idx_cgr_handler_personal_code ON erru.cgr_request (handler_personal_code);
CREATE INDEX idx_cgr_tm_first_name         ON erru.cgr_request (tm_first_name);
CREATE INDEX idx_cgr_tm_family_name        ON erru.cgr_request (tm_family_name);
CREATE INDEX idx_cgr_member_states_gin     ON erru.cgr_request USING GIN (member_states);

COMMENT ON INDEX erru.idx_cgr_key_ts IS 'Serves the latest-snapshot-per-key resolution used by every read path (DISTINCT ON / ORDER BY created_at DESC LIMIT 1).';

ALTER TABLE erru.cgr_request
    ADD CONSTRAINT chk_cgr_direction CHECK (direction IN ('outgoing', 'incoming')),
    ADD CONSTRAINT chk_cgr_status CHECK (status IN ('initiated', 'sent', 'received', 'answered', 'error')),
    ADD CONSTRAINT chk_cgr_status_matches_direction CHECK (
        status = 'error'
        OR (direction = 'outgoing' AND status IN ('initiated', 'sent'))
        OR (direction = 'incoming' AND status IN ('received', 'answered'))
    ),
    ADD CONSTRAINT chk_cgr_business_case_id_not_blank CHECK (btrim(business_case_id) <> ''),
    ADD CONSTRAINT chk_cgr_version_positive CHECK (version >= 1),
    ADD CONSTRAINT chk_cgr_cgr_to_format CHECK (cgr_to IS NULL OR cgr_to ~ '^[A-Z]{2}$'),
    ADD CONSTRAINT chk_cgr_search_choice CHECK (
        (
            COALESCE(btrim(tm_family_name), '') <> ''
            AND COALESCE(btrim(tm_first_name), '') <> ''
            AND tm_date_of_birth IS NOT NULL
        )
        OR
        (
            COALESCE(btrim(certificate_number), '') <> ''
            AND certificate_issue_date IS NOT NULL
            AND COALESCE(btrim(certificate_issue_country), '') <> ''
        )
    );

COMMENT ON CONSTRAINT chk_cgr_status_matches_direction ON erru.cgr_request IS 'Keeps the two status chains from leaking into each other: an outgoing request can never be received/answered and an incoming one can never be initiated/sent. error is shared by both directions.';
COMMENT ON CONSTRAINT chk_cgr_search_choice ON erru.cgr_request IS 'ERRU CGR is an XSD choice: SearchedTransportManager carries either a complete TransportManagerNameDetails (family name + first name + date of birth) or a complete TransportManagerCertificateDetails (certificate number + issue date + issue country), or both. Enforced in the database as defence in depth; the user-facing check lives in TEMPLATES/erru/cgr/validate-cgr-request.yml and applies to inbound requests too.';

CREATE UNIQUE INDEX uq_cgr_inbound_technical_id
    ON erru.cgr_request (technical_id)
    WHERE direction = 'incoming' AND status = 'received';

COMMENT ON INDEX erru.uq_cgr_inbound_technical_id IS 'Inbound idempotency. Partial index: technical_id repeats across later snapshots of the same message (answered, error), but there can be exactly one received row per technical_id. A redelivered ERRU message therefore cannot create a duplicate request. Heartbeat probes never reach this index because they are never persisted (see append-cgr-inbound.sql).';
