/*
declaration:
  version: 0.1
  description: "Look up the LATEST snapshot of an OUTGOING RSI message by its workflowId (LJVIS2-148). Used exclusively by the inbound-response handler to correlate the asynchronous response with the original outgoing send. RSI is an asynchronous exchange: after 'sent', the hub delivers the response as a separate call (Ruuter.internal inbound-response.yml) identified only by the workflowId that was generated by our side during the 'sent' transition. Returns zero rows when no outgoing message with this workflow_id exists (the caller treats that as an invalid response). CGR does not need this query because CGR is synchronous — there is no separate response correlation step in CGR."
  method: post
  accepts: json
  returns: json
  namespace: erru
  allowlist:
    body:
      - field: workflow_id
        type: string
  response:
    fields:
      - field: id
        type: number
      - field: version
        type: number
      - field: status
        type: string
      - field: direction
        type: string
      - field: business_case_id
        type: string
*/
SELECT
  rsi_message_key AS id,
  version,
  status,
  direction,
  business_case_id
FROM erru.rsi_message
WHERE workflow_id = :workflow_id::UUID
  AND direction = 'outgoing'
ORDER BY created_at DESC
LIMIT 1;
