/**
 * Eksporditava faili veergude eestikeelsed pealkirjad. Võti on andmebaasi
 * veeru nimi (või ekspordi enda tuletatud veerg). Puuduv võti jääb algnimeks.
 */
export const EXPORT_LABELS: Record<string, string> = {
  // — Ühised ja elutsükkel —
  id: 'Versiooni ID',
  version: 'Versioon',
  status: 'Olek',
  created_at: 'Loodud',
  created_by: 'Looja isikukood',
  form_number: 'Kontrollkaardi nr',
  sub_form_number: 'Alamvormi nr',
  notes: 'Märkused',
  files: 'Failid',
  extra_data: 'Lisaandmed',
  authority: 'Asutus',
  template_version: 'Malli versioon',

  // — Võtmed —
  compound_form_key: 'Koondvormi võti',
  foreign_violation_form_key: 'Välisriigi rikkumise vormi võti',
  labour_inspection_form_key: 'Tööinspektsiooni vormi võti',
  good_repute_form_key: 'Hea maine vormi võti',
  tram_control_card_key: 'TRAM-i kontrollkaardi võti',
  sp_driver_form_key: 'SP juhi vormi võti',
  sp_teammate_form_key: 'SP meeskonnaliikme vormi võti',
  vehicle_technical_form_key: 'Sõiduki tehnokaardi võti',
  trailer_technical_form_key: 'Haagise tehnokaardi võti',
  adr_form_key: 'ADR-vormi võti',
  kv_form_key: 'Vedamise katkestamise vormi võti',
  compound_form_number: 'Koondvormi nr',
  compound_status: 'Koondvormi olek',

  // — Kontrolli andmed —
  control_year: 'Kontrolli aasta',
  control_date: 'Kontrolli kuupäev',
  control_time: 'Kontrolli kellaaeg',
  control_country_code: 'Kontrolli riik',
  county: 'Maakond',
  city: 'Linn / vald',
  road: 'Tee',
  road_other: 'Tee (muu)',
  kilometer: 'Kilomeeter',
  address: 'Aadress',
  road_type: 'Tee liik',
  general_notes: 'Üldised märkused',
  road_tax_status: 'Teekasutustasu olek',
  road_tax_notes: 'Teekasutustasu märkused',

  // — Ametnik —
  inspector_first_name: 'Ametniku eesnimi',
  inspector_last_name: 'Ametniku perekonnanimi',
  inspector_name: 'Ametniku nimi',
  inspector_organisation_id: 'Ametniku asutuse ID',
  inspector_unit: 'Ametniku üksus',
  inspector_profession: 'Ametniku amet',

  // — Sõiduk —
  vehicle_reg_nr: 'Sõiduki reg-nr',
  vehicle_country_code: 'Sõiduki riik',
  vehicle_make: 'Sõiduki mark',
  vehicle_model: 'Sõiduki mudel',
  vehicle_vin: 'Sõiduki VIN-kood',
  vehicle_first_registration: 'Sõiduki esmane registreerimine',
  vehicle_body_type: 'Sõiduki keretüüp',
  vehicle_category_code: 'Sõiduki kategooria',
  vehicle_category_other: 'Sõiduki kategooria (muu)',
  vehicle_mileage: 'Sõiduki läbisõit',
  vehicle_count: 'Sõidukite arv',

  // — Haagis —
  trailers: 'Haagised (JSON)',
  trailer_reg_nr: 'Haagise reg-nr',

  // — Ettevõte —
  company_reg_code: 'Ettevõtte registrikood',
  company_name: 'Ettevõtte nimi',
  company_country_code: 'Vedaja riik',
  company_county: 'Ettevõtte maakond',
  company_city: 'Ettevõtte linn / vald',
  company_address: 'Ettevõtte aadress',
  company_postal_code: 'Ettevõtte postiindeks',
  company_owner_first_name: 'Ettevõtte omaniku eesnimi',
  company_owner_last_name: 'Ettevõtte omaniku perekonnanimi',
  company_activity_licence_copy_number: 'Tegevusloa ärakirja nr',
  company_address_line1: 'Ettevõtte aadress 1',
  company_address_line2: 'Ettevõtte aadress 2',
  company_region: 'Ettevõtte piirkond',
  licence_copy_number: 'Tegevusloa ärakirja nr',

  // — Juhid —
  drivers: 'Juhid (JSON)',
  drivers_extra: 'Lisajuhid (JSON)',
  driver_not_applicable: 'Juhti ei kohaldu',
  driver_last_name: 'Juhi perekonnanimi',
  driver_first_name: 'Juhi eesnimi',
  driver_birth_date: 'Juhi sünniaeg',
  driver_personal_code_ee: 'Juhi Eesti isikukood',
  driver_citizenship_code: 'Juhi kodakondsus',
  driver_personal_code_foreign: 'Juhi välisriigi isikukood',
  teammate_last_name: 'Meeskonnaliikme perekonnanimi',
  teammate_first_name: 'Meeskonnaliikme eesnimi',
  teammate_birth_date: 'Meeskonnaliikme sünniaeg',
  teammate_personal_code_ee: 'Meeskonnaliikme Eesti isikukood',
  teammate_citizenship_code: 'Meeskonnaliikme kodakondsus',
  teammate_personal_code_foreign: 'Meeskonnaliikme välisriigi isikukood',
  total_drivers_count: 'Juhtide koguarv',

  // — Välisriigi rikkumine —
  erru_message_id: 'ERRU teate ID',
  source_police_form_key: 'Lähtekontrollkaardi võti',
  data_entry_date: 'Andmete sisestamise kuupäev',
  reporting_country_code: 'Teavitav riik',
  reporting_authority_name: 'Teavitava asutuse nimi',
  inspection_date: 'Kontrolli kuupäev',
  inspection_time: 'Kontrolli kellaaeg',
  inspection_address_line1: 'Kontrolli aadress 1',
  inspection_address_line2: 'Kontrolli aadress 2',
  inspection_city: 'Kontrolli linn',
  inspection_region: 'Kontrolli piirkond',
  inspection_country_code: 'Kontrolli riik',
  inspection_type: 'Kontrolli liik',
  external_inspection_id: 'Välise kontrolli ID',
  violation_description: 'Rikkumise kirjeldus',
  minor_violations_count: 'Väiksemate rikkumiste arv',
  sanction_code: 'Sanktsioon',
  sanction_notes: 'Sanktsiooni märkused',
  violations: 'Rikkumised (JSON)',
  recommended_measure_code: 'Soovitatav meede',
  recommended_measure_notes: 'Soovitatava meetme märkused',
  additional_sanction_codes: 'Lisasanktsioonid',
  klim_clarification_date: 'KLIM-i selgituse kuupäev',
  carrier_explanation_date: 'Vedaja seletuse kuupäev',
  penalty_valid_until: 'Karistus kehtib kuni',
  penalty_expired_or_processed: 'Karistus aegunud või menetletud',
  akvk_next_meeting_date: 'AKVK järgmise koosoleku kuupäev',
  commission_last_decision_date: 'Komisjoni viimase otsuse kuupäev',
  admin_procedure_decision: 'Haldusmenetluse otsus',
  foreign_authority_proposal: 'Välisriigi asutuse ettepanek',
  notify_carrier: 'Teavita vedajat',
  erru_ncr_message_key: 'ERRU NCR teate võti',
  notify_labor_inspector: 'Teavita tööinspektorit',

  // — Tööinspektsioon —
  controls_matrix: 'Kontrollide maatriks (JSON)',
  prescription_composed: 'Ettekirjutus koostatud',
  punished_person_id_code: 'Karistatud isiku isikukood',
  punished_person_first_name: 'Karistatud isiku eesnimi',
  punished_person_last_name: 'Karistatud isiku perekonnanimi',

  // — Hea maine —
  personal_code: 'Isikukood',
  first_name: 'Eesnimi',
  last_name: 'Perekonnanimi',
  date_of_birth: 'Sünniaeg',
  place_of_birth: 'Sünnikoht',
  certificate_number: 'Tunnistuse nr',
  certificate_issue_date: 'Tunnistuse väljastamise kuupäev',
  certificate_country_code: 'Tunnistuse riik',
  fitness_status: 'Sobivuse olek',
  unfit_from_date: 'Sobimatu alates',
  unfit_until_date: 'Sobimatu kuni',

  // — TRAM / SP —
  transport_type: 'Veo liik',
  transport_empty_run: 'Tühisõit',
  transport_nature: 'Veo laad',
  transport_nature_exempt: 'Veo laadi erand',
  transport_classes: 'Veoklassid (JSON)',
  cabotage_violations: 'Kabotaažirikkumised (JSON)',
  result_type: 'Kontrolli tulemus',
  additional_measure: 'Lisameede',
  proceeding_type: 'Menetluse liik',
  proceeding_reference_number: 'Menetluse viitenumber',
  enforcement_decision: 'Täitevotsus',
  proceeding_closure_basis: 'Menetluse lõpetamise alus',
  document_checks: 'Dokumendikontrollid (JSON)',
  other_documents: 'Muud dokumendid (JSON)',
  sp_applicability: 'SP kohaldatavus',
  tachograph_type_code: 'Sõidumeerikuliik',
  tachograph_data_not_downloaded: 'Sõidumeeriku andmeid ei laaditud alla',
  tachograph_notes: 'Sõidumeeriku märkused',
  checked_days_count: 'Kontrollitud päevi',
  work_days_count: 'Tööpäevi',
  other_activity_days_count: 'Muu tegevuse päevi',
  violations_561_2006: 'Rikkumised: määrus 561/2006 (JSON)',
  violations_165_2014: 'Rikkumised: määrus 165/2014 (JSON)',
  violations_2002_15: 'Rikkumised: direktiiv 2002/15 (JSON)',
  violations_593_2008: 'Rikkumised: määrus 593/2008 (JSON)',
  violations_2020_1057: 'Rikkumised: direktiiv 2020/1057 (JSON)',
  erru_points: 'ERRU punktid (JSON)',
  liini_number: 'Liini number',
  liini_nimetus: 'Liini nimetus',
  selection_status: 'Valiku olek',
  mass_dimension_non_compliant: 'Mass/mõõtmed ei vasta nõuetele',
  mass_dimension_measurements: 'Massi/mõõtmete mõõtmised (JSON)',
  atp_violation_found: 'ATP rikkumine tuvastatud',
  atp_violation_description: 'ATP rikkumise kirjeldus',

  // — Tehnokaart —
  parts_summary: 'Osade kokkuvõte (JSON)',
  parts_defects: 'Osade rikked (JSON)',
  result_transport_interruption: 'Vedu katkestati',
  era_yv_mnt_regnr: 'Erakorraline: reg-nr',
  era_yv_mnt_vintin: 'Erakorraline: VIN/TIN',
  era_yv_mnt_axles: 'Erakorraline: teljed',
  era_yv_mnt_places: 'Erakorraline: kohad',
  era_yv_mnt_rebuilt: 'Erakorraline: ümberehitatud',
  extraordinary_inspection_date: 'Erakorralise ülevaatuse kuupäev',
  transport_interruption_autovs_51_3_1: 'Vedu katkestatud (AutoVS § 51 lg 3 p 1)',
  other_measure: 'Muu meede',

  // — ADR —
  driver_assistant: 'Juhi abi',
  driver_adr_certificate_number: 'Juhi ADR-tunnistuse nr',
  crew_adr_certificate_number: 'Meeskonna ADR-tunnistuse nr',
  assistant_adr_certificate_number: 'Abi ADR-tunnistuse nr',
  last_load_address: 'Viimase lasti aadress',
  last_load_date: 'Viimase lasti kuupäev',
  next_load_address: 'Järgmise lasti aadress',
  dangerous_goods: 'Ohtlikud veosed (JSON)',
  exemption_applied: 'Erandit kohaldati',
  exemption_adr_provision: 'Erandi ADR-säte',
  exemption_notes: 'Erandi märkused',
  container_type: 'Mahuti liik',
  container_types: 'Mahutite liigid',
  infringements: 'Rikkumised (JSON)',
  other_violations: 'Muud rikkumised',
  other_infringements: 'Muud rikkumised (JSON)',
  corrective_measures: 'Parandusmeetmed',
  seal_opened: 'Plomm avatud',
  seal_opened_date: 'Plommi avamise kuupäev',
  seal_installed_date: 'Plommi paigaldamise kuupäev',
  driving_ban_applied: 'Sõidukeeld kohaldatud',
  transport_interruption_applied: 'Vedu katkestati',
  infringement_notes_summary: 'Rikkumiste märkuste kokkuvõte',

  // — Vedamise katkestamine —
  header_text: 'Päisetekst',
  residence_country: 'Elukohariik',
  residence_region: 'Elukoha piirkond',
  residence_city: 'Elukoha linn',
  residence_address_line: 'Elukoha aadress',
  residence_postal_code: 'Elukoha postiindeks',
  interruption_reason: 'Katkestamise põhjus',
  legal_bases: 'Õiguslikud alused',
  termination_condition: 'Lõpetamise tingimus',
  person_applications: 'Isikute avaldused (JSON)',
};

/** Pealkirjad eestikeelseks; kordused saavad lõppu algnime, et veerud ei sulaks kokku. */
export function labelHeaders(keys: string[]): string[] {
  const used = new Map<string, number>();
  const labels = keys.map((k) => EXPORT_LABELS[k] ?? k);
  labels.forEach((l) => used.set(l, (used.get(l) ?? 0) + 1));
  return labels.map((l, i) => ((used.get(l) ?? 0) > 1 && l !== keys[i] ? `${l} (${keys[i]})` : l));
}
