export const BREAKPOINTS = {
  DESKTOP: 992,
} as const;

export const FORM_TYPE = {
  FOREIGN_VIOLATION: 'foreign-violation-form',
  COMPOUND: 'compound-form',
} as const;

export const PERMISSIONS = {
  USER_LIST_ADMIN: 'user.list.admin',
  USER_LIST_LOCAL: 'user.list.local',
  USER_GROUP_LIST_ADMIN: 'user_group.list.admin',
  USER_GROUP_LIST_LOCAL: 'user_group.list.local',
  CLASSIFIER_LIST: 'classifier.list',
  AUDIT_READ: 'audit.read',
} as const;

export const DESKTOP = {
  DASHBOARD_MANUAL_ADD: 'DASHBOARD_MANUAL_ADD',
  DASHBOARD_EXCLUDED: 'DASHBOARD_EXCLUDED',
} as const;

export const OTHER = {
  ROAD: 'muu_tee',
  TRAILER_CATEGORY: 'OTHER_2012',
  VEHICLE_CATEGORY: 'OTHER_2012',
} as const;

export const ROAD = {
  NATIONAL: 'Riigimaantee',
  LOCAL: 'Kohalik tee',
  TAX_STATUS_NOT_APPLICABLE: 'Ei kohaldu',
} as const;

export const EU_VIOLATION_GROUPS = [
  {
    id: 'msi',
    labelKey: 'forms.foreign_violation.euViolationGroupMsi',
    items: [
      {
        value: 'MSI101',
        labelKey: 'forms.foreign_violation.euViolationMsi101',
      },
      {
        value: 'MSI102',
        labelKey: 'forms.foreign_violation.euViolationMsi102',
      },
      {
        value: 'MSI103',
        labelKey: 'forms.foreign_violation.euViolationMsi103',
      },
      {
        value: 'MSI104',
        labelKey: 'forms.foreign_violation.euViolationMsi104',
      },
      {
        value: 'MSI201',
        labelKey: 'forms.foreign_violation.euViolationMsi201',
      },
      {
        value: 'MSI202',
        labelKey: 'forms.foreign_violation.euViolationMsi202',
      },
      {
        value: 'MSI203',
        labelKey: 'forms.foreign_violation.euViolationMsi203',
      },
      {
        value: 'MSI204',
        labelKey: 'forms.foreign_violation.euViolationMsi204',
      },
      {
        value: 'MSI205',
        labelKey: 'forms.foreign_violation.euViolationMsi205',
      },
      {
        value: 'MSI301',
        labelKey: 'forms.foreign_violation.euViolationMsi301',
      },
      {
        value: 'MSI302',
        labelKey: 'forms.foreign_violation.euViolationMsi302',
      },
      {
        value: 'MSI401',
        labelKey: 'forms.foreign_violation.euViolationMsi401',
      },
      {
        value: 'MSI402',
        labelKey: 'forms.foreign_violation.euViolationMsi402',
      },
      {
        value: 'MSI403',
        labelKey: 'forms.foreign_violation.euViolationMsi403',
      },
      {
        value: 'MSI501',
        labelKey: 'forms.foreign_violation.euViolationMsi501',
      },
      {
        value: 'MSI503',
        labelKey: 'forms.foreign_violation.euViolationMsi503',
      },
      {
        value: 'MSI504',
        labelKey: 'forms.foreign_violation.euViolationMsi504',
      },
      {
        value: 'MSI601',
        labelKey: 'forms.foreign_violation.euViolationMsi601',
      },
      {
        value: 'MSI602',
        labelKey: 'forms.foreign_violation.euViolationMsi602',
      },
      {
        value: 'MSI603',
        labelKey: 'forms.foreign_violation.euViolationMsi603',
      },
      {
        value: 'MSI701',
        labelKey: 'forms.foreign_violation.euViolationMsi701',
      },
      {
        value: 'MSI702',
        labelKey: 'forms.foreign_violation.euViolationMsi702',
      },
    ],
  },
  {
    id: 'vsi',
    labelKey: 'forms.foreign_violation.euViolationGroupVsi',
    items: [
      {
        value: 'VSI847',
        labelKey: 'forms.foreign_violation.euViolationVsi847',
      },
      {
        value: 'VSI800',
        labelKey: 'forms.foreign_violation.euViolationVsi800',
      },
      {
        value: 'VSI801',
        labelKey: 'forms.foreign_violation.euViolationVsi801',
      },
      {
        value: 'VSI802',
        labelKey: 'forms.foreign_violation.euViolationVsi802',
      },
      {
        value: 'VSI803',
        labelKey: 'forms.foreign_violation.euViolationVsi803',
      },
      {
        value: 'VSI804',
        labelKey: 'forms.foreign_violation.euViolationVsi804',
      },
      {
        value: 'VSI805',
        labelKey: 'forms.foreign_violation.euViolationVsi805',
      },
      {
        value: 'VSI806',
        labelKey: 'forms.foreign_violation.euViolationVsi806',
      },
      {
        value: 'VSI807',
        labelKey: 'forms.foreign_violation.euViolationVsi807',
      },
      {
        value: 'VSI808',
        labelKey: 'forms.foreign_violation.euViolationVsi808',
      },
      {
        value: 'VSI809',
        labelKey: 'forms.foreign_violation.euViolationVsi809',
      },
      {
        value: 'VSI810',
        labelKey: 'forms.foreign_violation.euViolationVsi810',
      },
      {
        value: 'VSI811',
        labelKey: 'forms.foreign_violation.euViolationVsi811',
      },
      {
        value: 'VSI812',
        labelKey: 'forms.foreign_violation.euViolationVsi812',
      },
      {
        value: 'VSI813',
        labelKey: 'forms.foreign_violation.euViolationVsi813',
      },
      {
        value: 'VSI814',
        labelKey: 'forms.foreign_violation.euViolationVsi814',
      },
      {
        value: 'VSI815',
        labelKey: 'forms.foreign_violation.euViolationVsi815',
      },
      {
        value: 'VSI816',
        labelKey: 'forms.foreign_violation.euViolationVsi816',
      },
      {
        value: 'VSI817',
        labelKey: 'forms.foreign_violation.euViolationVsi817',
      },
      {
        value: 'VSI818',
        labelKey: 'forms.foreign_violation.euViolationVsi818',
      },
      {
        value: 'VSI819',
        labelKey: 'forms.foreign_violation.euViolationVsi819',
      },
      {
        value: 'VSI820',
        labelKey: 'forms.foreign_violation.euViolationVsi820',
      },
      {
        value: 'VSI821',
        labelKey: 'forms.foreign_violation.euViolationVsi821',
      },
      {
        value: 'VSI822',
        labelKey: 'forms.foreign_violation.euViolationVsi822',
      },
      {
        value: 'VSI823',
        labelKey: 'forms.foreign_violation.euViolationVsi823',
      },
      {
        value: 'VSI824',
        labelKey: 'forms.foreign_violation.euViolationVsi824',
      },
      {
        value: 'VSI825',
        labelKey: 'forms.foreign_violation.euViolationVsi825',
      },
      {
        value: 'VSI826',
        labelKey: 'forms.foreign_violation.euViolationVsi826',
      },
      {
        value: 'VSI827',
        labelKey: 'forms.foreign_violation.euViolationVsi827',
      },
      {
        value: 'VSI828',
        labelKey: 'forms.foreign_violation.euViolationVsi828',
      },
      {
        value: 'VSI829',
        labelKey: 'forms.foreign_violation.euViolationVsi829',
      },
      {
        value: 'VSI833',
        labelKey: 'forms.foreign_violation.euViolationVsi833',
      },
      {
        value: 'VSI834',
        labelKey: 'forms.foreign_violation.euViolationVsi834',
      },
      {
        value: 'VSI835',
        labelKey: 'forms.foreign_violation.euViolationVsi835',
      },
      {
        value: 'VSI836',
        labelKey: 'forms.foreign_violation.euViolationVsi836',
      },
      {
        value: 'VSI837',
        labelKey: 'forms.foreign_violation.euViolationVsi837',
      },
      {
        value: 'VSI838',
        labelKey: 'forms.foreign_violation.euViolationVsi838',
      },
      {
        value: 'VSI839',
        labelKey: 'forms.foreign_violation.euViolationVsi839',
      },
      {
        value: 'VSI840',
        labelKey: 'forms.foreign_violation.euViolationVsi840',
      },
      {
        value: 'VSI841',
        labelKey: 'forms.foreign_violation.euViolationVsi841',
      },
      {
        value: 'VSI842',
        labelKey: 'forms.foreign_violation.euViolationVsi842',
      },
      {
        value: 'VSI843',
        labelKey: 'forms.foreign_violation.euViolationVsi843',
      },
      {
        value: 'VSI844',
        labelKey: 'forms.foreign_violation.euViolationVsi844',
      },
      {
        value: 'VSI845',
        labelKey: 'forms.foreign_violation.euViolationVsi845',
      },
      {
        value: 'VSI846',
        labelKey: 'forms.foreign_violation.euViolationVsi846',
      },
      {
        value: 'VSI848',
        labelKey: 'forms.foreign_violation.euViolationVsi848',
      },
      {
        value: 'VSI849',
        labelKey: 'forms.foreign_violation.euViolationVsi849',
      },
      {
        value: 'VSI850',
        labelKey: 'forms.foreign_violation.euViolationVsi850',
      },
      {
        value: 'VSI851',
        labelKey: 'forms.foreign_violation.euViolationVsi851',
      },
      {
        value: 'VSI852',
        labelKey: 'forms.foreign_violation.euViolationVsi852',
      },
      {
        value: 'VSI853',
        labelKey: 'forms.foreign_violation.euViolationVsi853',
      },
      {
        value: 'VSI854',
        labelKey: 'forms.foreign_violation.euViolationVsi854',
      },
      {
        value: 'VSI855',
        labelKey: 'forms.foreign_violation.euViolationVsi855',
      },
      {
        value: 'VSI856',
        labelKey: 'forms.foreign_violation.euViolationVsi856',
      },
      {
        value: 'VSI857',
        labelKey: 'forms.foreign_violation.euViolationVsi857',
      },
      {
        value: 'VSI858',
        labelKey: 'forms.foreign_violation.euViolationVsi858',
      },
      {
        value: 'VSI859',
        labelKey: 'forms.foreign_violation.euViolationVsi859',
      },
      {
        value: 'VSI860',
        labelKey: 'forms.foreign_violation.euViolationVsi860',
      },
      {
        value: 'VSI861',
        labelKey: 'forms.foreign_violation.euViolationVsi861',
      },
      {
        value: 'VSI862',
        labelKey: 'forms.foreign_violation.euViolationVsi862',
      },
      {
        value: 'VSI863',
        labelKey: 'forms.foreign_violation.euViolationVsi863',
      },
      {
        value: 'VSI864',
        labelKey: 'forms.foreign_violation.euViolationVsi864',
      },
      {
        value: 'VSI875',
        labelKey: 'forms.foreign_violation.euViolationVsi875',
      },
      {
        value: 'VSI876',
        labelKey: 'forms.foreign_violation.euViolationVsi876',
      },
      {
        value: 'VSI877',
        labelKey: 'forms.foreign_violation.euViolationVsi877',
      },
      {
        value: 'VSI878',
        labelKey: 'forms.foreign_violation.euViolationVsi878',
      },
      {
        value: 'VSI879',
        labelKey: 'forms.foreign_violation.euViolationVsi879',
      },
      {
        value: 'VSI865',
        labelKey: 'forms.foreign_violation.euViolationVsi865',
      },
      {
        value: 'VSI866',
        labelKey: 'forms.foreign_violation.euViolationVsi866',
      },
      {
        value: 'VSI867',
        labelKey: 'forms.foreign_violation.euViolationVsi867',
      },
      {
        value: 'VSI868',
        labelKey: 'forms.foreign_violation.euViolationVsi868',
      },
      {
        value: 'VSI869',
        labelKey: 'forms.foreign_violation.euViolationVsi869',
      },
      {
        value: 'VSI870',
        labelKey: 'forms.foreign_violation.euViolationVsi870',
      },
      {
        value: 'VSI871',
        labelKey: 'forms.foreign_violation.euViolationVsi871',
      },
      {
        value: 'VSI872',
        labelKey: 'forms.foreign_violation.euViolationVsi872',
      },
      {
        value: 'VSI873',
        labelKey: 'forms.foreign_violation.euViolationVsi873',
      },
      {
        value: 'VSI874',
        labelKey: 'forms.foreign_violation.euViolationVsi874',
      },
      {
        value: 'VSI832',
        labelKey: 'forms.foreign_violation.euViolationVsi832',
      },
    ],
  },
  {
    id: 'si',
    labelKey: 'forms.foreign_violation.euViolationGroupSi',
    items: [
      { value: 'SI926', labelKey: 'forms.foreign_violation.euViolationSi926' },
      { value: 'SI900', labelKey: 'forms.foreign_violation.euViolationSi900' },
      { value: 'SI901', labelKey: 'forms.foreign_violation.euViolationSi901' },
      { value: 'SI902', labelKey: 'forms.foreign_violation.euViolationSi902' },
      { value: 'SI903', labelKey: 'forms.foreign_violation.euViolationSi903' },
      { value: 'SI904', labelKey: 'forms.foreign_violation.euViolationSi904' },
      { value: 'SI905', labelKey: 'forms.foreign_violation.euViolationSi905' },
      { value: 'SI906', labelKey: 'forms.foreign_violation.euViolationSi906' },
      { value: 'SI907', labelKey: 'forms.foreign_violation.euViolationSi907' },
      { value: 'SI908', labelKey: 'forms.foreign_violation.euViolationSi908' },
      { value: 'SI909', labelKey: 'forms.foreign_violation.euViolationSi909' },
      { value: 'SI910', labelKey: 'forms.foreign_violation.euViolationSi910' },
      { value: 'SI911', labelKey: 'forms.foreign_violation.euViolationSi911' },
      { value: 'SI912', labelKey: 'forms.foreign_violation.euViolationSi912' },
      { value: 'SI913', labelKey: 'forms.foreign_violation.euViolationSi913' },
      { value: 'SI914', labelKey: 'forms.foreign_violation.euViolationSi914' },
      { value: 'SI915', labelKey: 'forms.foreign_violation.euViolationSi915' },
      { value: 'SI916', labelKey: 'forms.foreign_violation.euViolationSi916' },
      { value: 'SI917', labelKey: 'forms.foreign_violation.euViolationSi917' },
      { value: 'SI918', labelKey: 'forms.foreign_violation.euViolationSi918' },
      { value: 'SI919', labelKey: 'forms.foreign_violation.euViolationSi919' },
      { value: 'SI920', labelKey: 'forms.foreign_violation.euViolationSi920' },
      { value: 'SI921', labelKey: 'forms.foreign_violation.euViolationSi921' },
      { value: 'SI922', labelKey: 'forms.foreign_violation.euViolationSi922' },
      { value: 'SI923', labelKey: 'forms.foreign_violation.euViolationSi923' },
      { value: 'SI924', labelKey: 'forms.foreign_violation.euViolationSi924' },
      { value: 'SI925', labelKey: 'forms.foreign_violation.euViolationSi925' },
      { value: 'SI927', labelKey: 'forms.foreign_violation.euViolationSi927' },
      { value: 'SI928', labelKey: 'forms.foreign_violation.euViolationSi928' },
      { value: 'SI929', labelKey: 'forms.foreign_violation.euViolationSi929' },
      { value: 'SI930', labelKey: 'forms.foreign_violation.euViolationSi930' },
      { value: 'SI931', labelKey: 'forms.foreign_violation.euViolationSi931' },
      { value: 'SI932', labelKey: 'forms.foreign_violation.euViolationSi932' },
      { value: 'SI933', labelKey: 'forms.foreign_violation.euViolationSi933' },
      { value: 'SI934', labelKey: 'forms.foreign_violation.euViolationSi934' },
      { value: 'SI935', labelKey: 'forms.foreign_violation.euViolationSi935' },
      { value: 'SI936', labelKey: 'forms.foreign_violation.euViolationSi936' },
      { value: 'SI937', labelKey: 'forms.foreign_violation.euViolationSi937' },
      { value: 'SI938', labelKey: 'forms.foreign_violation.euViolationSi938' },
      { value: 'SI939', labelKey: 'forms.foreign_violation.euViolationSi939' },
      { value: 'SI940', labelKey: 'forms.foreign_violation.euViolationSi940' },
      { value: 'SI941', labelKey: 'forms.foreign_violation.euViolationSi941' },
      { value: 'SI942', labelKey: 'forms.foreign_violation.euViolationSi942' },
      { value: 'SI943', labelKey: 'forms.foreign_violation.euViolationSi943' },
      { value: 'SI944', labelKey: 'forms.foreign_violation.euViolationSi944' },
      { value: 'SI945', labelKey: 'forms.foreign_violation.euViolationSi945' },
      { value: 'SI946', labelKey: 'forms.foreign_violation.euViolationSi946' },
      { value: 'SI951', labelKey: 'forms.foreign_violation.euViolationSi951' },
      { value: 'SI952', labelKey: 'forms.foreign_violation.euViolationSi952' },
      { value: 'SI947', labelKey: 'forms.foreign_violation.euViolationSi947' },
      { value: 'SI948', labelKey: 'forms.foreign_violation.euViolationSi948' },
      { value: 'SI949', labelKey: 'forms.foreign_violation.euViolationSi949' },
      { value: 'SI950', labelKey: 'forms.foreign_violation.euViolationSi950' },
    ],
  },
];

export const COUNTRIES = [
  { value: 'AD', labelKey: 'countries.AD' },
  { value: 'AE', labelKey: 'countries.AE' },
  { value: 'AF', labelKey: 'countries.AF' },
  { value: 'AG', labelKey: 'countries.AG' },
  { value: 'AI', labelKey: 'countries.AI' },
  { value: 'AL', labelKey: 'countries.AL' },
  { value: 'AM', labelKey: 'countries.AM' },
  { value: 'AO', labelKey: 'countries.AO' },
  { value: 'AQ', labelKey: 'countries.AQ' },
  { value: 'AR', labelKey: 'countries.AR' },
  { value: 'AS', labelKey: 'countries.AS' },
  { value: 'AT', labelKey: 'countries.AT' },
  { value: 'AU', labelKey: 'countries.AU' },
  { value: 'AW', labelKey: 'countries.AW' },
  { value: 'AX', labelKey: 'countries.AX' },
  { value: 'AZ', labelKey: 'countries.AZ' },
  { value: 'BA', labelKey: 'countries.BA' },
  { value: 'BB', labelKey: 'countries.BB' },
  { value: 'BD', labelKey: 'countries.BD' },
  { value: 'BE', labelKey: 'countries.BE' },
  { value: 'BF', labelKey: 'countries.BF' },
  { value: 'BG', labelKey: 'countries.BG' },
  { value: 'BH', labelKey: 'countries.BH' },
  { value: 'BI', labelKey: 'countries.BI' },
  { value: 'BJ', labelKey: 'countries.BJ' },
  { value: 'BL', labelKey: 'countries.BL' },
  { value: 'BM', labelKey: 'countries.BM' },
  { value: 'BN', labelKey: 'countries.BN' },
  { value: 'BO', labelKey: 'countries.BO' },
  { value: 'BQ', labelKey: 'countries.BQ' },
  { value: 'BR', labelKey: 'countries.BR' },
  { value: 'BS', labelKey: 'countries.BS' },
  { value: 'BT', labelKey: 'countries.BT' },
  { value: 'BV', labelKey: 'countries.BV' },
  { value: 'BW', labelKey: 'countries.BW' },
  { value: 'BY', labelKey: 'countries.BY' },
  { value: 'BZ', labelKey: 'countries.BZ' },
  { value: 'CA', labelKey: 'countries.CA' },
  { value: 'CC', labelKey: 'countries.CC' },
  { value: 'CD', labelKey: 'countries.CD' },
  { value: 'CF', labelKey: 'countries.CF' },
  { value: 'CG', labelKey: 'countries.CG' },
  { value: 'CH', labelKey: 'countries.CH' },
  { value: 'CI', labelKey: 'countries.CI' },
  { value: 'CK', labelKey: 'countries.CK' },
  { value: 'CL', labelKey: 'countries.CL' },
  { value: 'CM', labelKey: 'countries.CM' },
  { value: 'CN', labelKey: 'countries.CN' },
  { value: 'CO', labelKey: 'countries.CO' },
  { value: 'CR', labelKey: 'countries.CR' },
  { value: 'CU', labelKey: 'countries.CU' },
  { value: 'CV', labelKey: 'countries.CV' },
  { value: 'CW', labelKey: 'countries.CW' },
  { value: 'CX', labelKey: 'countries.CX' },
  { value: 'CY', labelKey: 'countries.CY' },
  { value: 'CZ', labelKey: 'countries.CZ' },
  { value: 'DE', labelKey: 'countries.DE' },
  { value: 'DJ', labelKey: 'countries.DJ' },
  { value: 'DK', labelKey: 'countries.DK' },
  { value: 'DM', labelKey: 'countries.DM' },
  { value: 'DO', labelKey: 'countries.DO' },
  { value: 'DZ', labelKey: 'countries.DZ' },
  { value: 'EC', labelKey: 'countries.EC' },
  { value: 'EE', labelKey: 'countries.EE' },
  { value: 'EG', labelKey: 'countries.EG' },
  { value: 'EH', labelKey: 'countries.EH' },
  { value: 'ER', labelKey: 'countries.ER' },
  { value: 'ES', labelKey: 'countries.ES' },
  { value: 'ET', labelKey: 'countries.ET' },
  { value: 'FI', labelKey: 'countries.FI' },
  { value: 'FJ', labelKey: 'countries.FJ' },
  { value: 'FK', labelKey: 'countries.FK' },
  { value: 'FM', labelKey: 'countries.FM' },
  { value: 'FO', labelKey: 'countries.FO' },
  { value: 'FR', labelKey: 'countries.FR' },
  { value: 'GA', labelKey: 'countries.GA' },
  { value: 'GB', labelKey: 'countries.GB' },
  { value: 'GD', labelKey: 'countries.GD' },
  { value: 'GE', labelKey: 'countries.GE' },
  { value: 'GF', labelKey: 'countries.GF' },
  { value: 'GG', labelKey: 'countries.GG' },
  { value: 'GH', labelKey: 'countries.GH' },
  { value: 'GI', labelKey: 'countries.GI' },
  { value: 'GL', labelKey: 'countries.GL' },
  { value: 'GM', labelKey: 'countries.GM' },
  { value: 'GN', labelKey: 'countries.GN' },
  { value: 'GP', labelKey: 'countries.GP' },
  { value: 'GQ', labelKey: 'countries.GQ' },
  { value: 'GR', labelKey: 'countries.GR' },
  { value: 'GS', labelKey: 'countries.GS' },
  { value: 'GT', labelKey: 'countries.GT' },
  { value: 'GU', labelKey: 'countries.GU' },
  { value: 'GW', labelKey: 'countries.GW' },
  { value: 'GY', labelKey: 'countries.GY' },
  { value: 'HK', labelKey: 'countries.HK' },
  { value: 'HM', labelKey: 'countries.HM' },
  { value: 'HN', labelKey: 'countries.HN' },
  { value: 'HR', labelKey: 'countries.HR' },
  { value: 'HT', labelKey: 'countries.HT' },
  { value: 'HU', labelKey: 'countries.HU' },
  { value: 'ID', labelKey: 'countries.ID' },
  { value: 'IE', labelKey: 'countries.IE' },
  { value: 'IL', labelKey: 'countries.IL' },
  { value: 'IM', labelKey: 'countries.IM' },
  { value: 'IN', labelKey: 'countries.IN' },
  { value: 'IO', labelKey: 'countries.IO' },
  { value: 'IQ', labelKey: 'countries.IQ' },
  { value: 'IR', labelKey: 'countries.IR' },
  { value: 'IS', labelKey: 'countries.IS' },
  { value: 'IT', labelKey: 'countries.IT' },
  { value: 'JE', labelKey: 'countries.JE' },
  { value: 'JM', labelKey: 'countries.JM' },
  { value: 'JO', labelKey: 'countries.JO' },
  { value: 'JP', labelKey: 'countries.JP' },
  { value: 'KE', labelKey: 'countries.KE' },
  { value: 'KG', labelKey: 'countries.KG' },
  { value: 'KH', labelKey: 'countries.KH' },
  { value: 'KI', labelKey: 'countries.KI' },
  { value: 'KM', labelKey: 'countries.KM' },
  { value: 'KN', labelKey: 'countries.KN' },
  { value: 'KP', labelKey: 'countries.KP' },
  { value: 'KR', labelKey: 'countries.KR' },
  { value: 'KW', labelKey: 'countries.KW' },
  { value: 'KY', labelKey: 'countries.KY' },
  { value: 'KZ', labelKey: 'countries.KZ' },
  { value: 'LA', labelKey: 'countries.LA' },
  { value: 'LB', labelKey: 'countries.LB' },
  { value: 'LC', labelKey: 'countries.LC' },
  { value: 'LI', labelKey: 'countries.LI' },
  { value: 'LK', labelKey: 'countries.LK' },
  { value: 'LR', labelKey: 'countries.LR' },
  { value: 'LS', labelKey: 'countries.LS' },
  { value: 'LT', labelKey: 'countries.LT' },
  { value: 'LU', labelKey: 'countries.LU' },
  { value: 'LV', labelKey: 'countries.LV' },
  { value: 'LY', labelKey: 'countries.LY' },
  { value: 'MA', labelKey: 'countries.MA' },
  { value: 'MC', labelKey: 'countries.MC' },
  { value: 'MD', labelKey: 'countries.MD' },
  { value: 'ME', labelKey: 'countries.ME' },
  { value: 'MF', labelKey: 'countries.MF' },
  { value: 'MG', labelKey: 'countries.MG' },
  { value: 'MH', labelKey: 'countries.MH' },
  { value: 'MK', labelKey: 'countries.MK' },
  { value: 'ML', labelKey: 'countries.ML' },
  { value: 'MM', labelKey: 'countries.MM' },
  { value: 'MN', labelKey: 'countries.MN' },
  { value: 'MO', labelKey: 'countries.MO' },
  { value: 'MP', labelKey: 'countries.MP' },
  { value: 'MQ', labelKey: 'countries.MQ' },
  { value: 'MR', labelKey: 'countries.MR' },
  { value: 'MS', labelKey: 'countries.MS' },
  { value: 'MT', labelKey: 'countries.MT' },
  { value: 'MU', labelKey: 'countries.MU' },
  { value: 'MV', labelKey: 'countries.MV' },
  { value: 'MW', labelKey: 'countries.MW' },
  { value: 'MX', labelKey: 'countries.MX' },
  { value: 'MY', labelKey: 'countries.MY' },
  { value: 'MZ', labelKey: 'countries.MZ' },
  { value: 'NA', labelKey: 'countries.NA' },
  { value: 'NC', labelKey: 'countries.NC' },
  { value: 'NE', labelKey: 'countries.NE' },
  { value: 'NF', labelKey: 'countries.NF' },
  { value: 'NG', labelKey: 'countries.NG' },
  { value: 'NI', labelKey: 'countries.NI' },
  { value: 'NL', labelKey: 'countries.NL' },
  { value: 'NO', labelKey: 'countries.NO' },
  { value: 'NP', labelKey: 'countries.NP' },
  { value: 'NR', labelKey: 'countries.NR' },
  { value: 'NU', labelKey: 'countries.NU' },
  { value: 'NZ', labelKey: 'countries.NZ' },
  { value: 'OM', labelKey: 'countries.OM' },
  { value: 'PA', labelKey: 'countries.PA' },
  { value: 'PE', labelKey: 'countries.PE' },
  { value: 'PF', labelKey: 'countries.PF' },
  { value: 'PG', labelKey: 'countries.PG' },
  { value: 'PH', labelKey: 'countries.PH' },
  { value: 'PK', labelKey: 'countries.PK' },
  { value: 'PL', labelKey: 'countries.PL' },
  { value: 'PM', labelKey: 'countries.PM' },
  { value: 'PN', labelKey: 'countries.PN' },
  { value: 'PR', labelKey: 'countries.PR' },
  { value: 'PS', labelKey: 'countries.PS' },
  { value: 'PT', labelKey: 'countries.PT' },
  { value: 'PW', labelKey: 'countries.PW' },
  { value: 'PY', labelKey: 'countries.PY' },
  { value: 'QA', labelKey: 'countries.QA' },
  { value: 'RE', labelKey: 'countries.RE' },
  { value: 'RO', labelKey: 'countries.RO' },
  { value: 'RS', labelKey: 'countries.RS' },
  { value: 'RU', labelKey: 'countries.RU' },
  { value: 'RW', labelKey: 'countries.RW' },
  { value: 'SA', labelKey: 'countries.SA' },
  { value: 'SB', labelKey: 'countries.SB' },
  { value: 'SC', labelKey: 'countries.SC' },
  { value: 'SD', labelKey: 'countries.SD' },
  { value: 'SE', labelKey: 'countries.SE' },
  { value: 'SG', labelKey: 'countries.SG' },
  { value: 'SH', labelKey: 'countries.SH' },
  { value: 'SI', labelKey: 'countries.SI' },
  { value: 'SJ', labelKey: 'countries.SJ' },
  { value: 'SK', labelKey: 'countries.SK' },
  { value: 'SL', labelKey: 'countries.SL' },
  { value: 'SM', labelKey: 'countries.SM' },
  { value: 'SN', labelKey: 'countries.SN' },
  { value: 'SO', labelKey: 'countries.SO' },
  { value: 'SR', labelKey: 'countries.SR' },
  { value: 'SS', labelKey: 'countries.SS' },
  { value: 'ST', labelKey: 'countries.ST' },
  { value: 'SV', labelKey: 'countries.SV' },
  { value: 'SX', labelKey: 'countries.SX' },
  { value: 'SY', labelKey: 'countries.SY' },
  { value: 'SZ', labelKey: 'countries.SZ' },
  { value: 'TC', labelKey: 'countries.TC' },
  { value: 'TD', labelKey: 'countries.TD' },
  { value: 'TF', labelKey: 'countries.TF' },
  { value: 'TG', labelKey: 'countries.TG' },
  { value: 'TH', labelKey: 'countries.TH' },
  { value: 'TJ', labelKey: 'countries.TJ' },
  { value: 'TK', labelKey: 'countries.TK' },
  { value: 'TL', labelKey: 'countries.TL' },
  { value: 'TM', labelKey: 'countries.TM' },
  { value: 'TN', labelKey: 'countries.TN' },
  { value: 'TO', labelKey: 'countries.TO' },
  { value: 'TR', labelKey: 'countries.TR' },
  { value: 'TT', labelKey: 'countries.TT' },
  { value: 'TV', labelKey: 'countries.TV' },
  { value: 'TW', labelKey: 'countries.TW' },
  { value: 'TZ', labelKey: 'countries.TZ' },
  { value: 'UA', labelKey: 'countries.UA' },
  { value: 'UG', labelKey: 'countries.UG' },
  { value: 'UM', labelKey: 'countries.UM' },
  { value: 'US', labelKey: 'countries.US' },
  { value: 'UY', labelKey: 'countries.UY' },
  { value: 'UZ', labelKey: 'countries.UZ' },
  { value: 'VA', labelKey: 'countries.VA' },
  { value: 'VC', labelKey: 'countries.VC' },
  { value: 'VE', labelKey: 'countries.VE' },
  { value: 'VG', labelKey: 'countries.VG' },
  { value: 'VI', labelKey: 'countries.VI' },
  { value: 'VN', labelKey: 'countries.VN' },
  { value: 'VU', labelKey: 'countries.VU' },
  { value: 'WF', labelKey: 'countries.WF' },
  { value: 'WS', labelKey: 'countries.WS' },
  { value: 'YE', labelKey: 'countries.YE' },
  { value: 'YT', labelKey: 'countries.YT' },
  { value: 'ZA', labelKey: 'countries.ZA' },
  { value: 'ZM', labelKey: 'countries.ZM' },
  { value: 'ZW', labelKey: 'countries.ZW' },
];

export const FORM_STATUS_KEY: Record<string, string> = {
  saved: 'forms.foreign_violation.statusSaved',
  confirmed: 'forms.foreign_violation.statusConfirmed',
  published: 'forms.foreign_violation.statusPublished',
  deleted: 'forms.foreign_violation.statusDeleted',
};
