# Nõutav õigus: user.list.admin,user.list.local. auth_user tuleb projektiülesest guardist (ljvis/.guard.yml).
check:
  switch:
    - condition: ${auth_user.permissions != null && (auth_user.permissions.includes('user.list.admin') || auth_user.permissions.includes('user.list.local'))}
      next: allow
  next: deny

allow:
  status: 200
  return: "ok"
  next: end

deny:
  status: 403
  return: "forbidden"
  next: end
