"""Generate reproducible, wholly synthetic blank and filled review documents."""
import copy,json
from pathlib import Path
from render import ROOT, TEMPLATES, render_html, render_pdf
c=json.loads((ROOT/'examples/filled.json').read_text())['compoundForm']
c.update(vehicleVin='TESTVIN0000000001',vehicleCategoryCode='B_2012',vehicleMileage='125000',vehicleMake='Näidismark',vehicleModel='Proovimudel',companyActivityLicenceCopyNumber='NÄIDIS-123')
c['drivers'][0].update(citizenshipCode='EE',birthDate='1990-01-01')
c['trailers'][0].update(make='Näidishaagis',model='Proov',categoryCode='D_2012',vin='TRAILERTEST001')
base={'compoundForm':c,'labels':{'countries':{'EE':'Eesti'},'organisations':{'DEMO':'Näidisasutus'}}}
payloads={}
payloads['compound-form']={'compoundForm':copy.deepcopy(c),'labels':copy.deepcopy(base['labels'])}
payloads['foreign-violation-form']={'foreignViolationForm':{'id':'7001','formNumber':'NÄIDIS-VR-001','version':1,'status':'published','reportingCountryCode':'LV','reportingAuthority':'Näidisamet','inspectionCountryCode':'LV','inspectionDate':'2026-09-08','inspectionTime':'09:25','inspectionAddressLine1':'Näidise iela 1','inspectionRegion':'Riia piirkond','inspectionCity':'Riia','companyRegCode':'TEST-7001','companyName':'Näidisvedaja OÜ','companyCountryCode':'EE','companyAddressLine1':'Näidise tee 7','companyCity':'Tallinn','companyPostalCode':'10000','driverFirstName':'Test','driverLastName':'Juht','vehicleRegNr':'TEST123','vehicleMake':'Näidismark','vehicleModel':'Mudel','vehicleCountryCode':'EE','vehicleVin':'TESTVIN7001','vehicleFirstRegistration':'2020-01-02','licenceCopyNumber':'LIC-TEST','violationDescription':'Sünteetiline rikkumise kirjeldus kujunduse kontrollimiseks.','minorViolationsCount':'1','sanctionCode':'WARNING','sanctionNotes':'Näidismärkus','additionalSanctionCodes':['DEMO'],'violations':['VSI800'],'recommendedMeasureCode':'DEMO','recommendedMeasureNotes':'Näidismeede','notes':'Sünteetilised andmed.','dataEntryDate':'2026-09-09','inspectorFirstName':'Test','inspectorLastName':'Inspektor','inspectorOrganisationId':'DEMO','inspectorUnit':'TEST','inspectorProfession':'inspektor','klimClarificationDate':'2026-09-09','penaltyExpiredOrProcessed':False,'foreignAuthorityProposal':True,'notifyCarrier':False},'labels':copy.deepcopy(base['labels'])}
payloads['labour-inspection']={'labourInspectionForm':{'id':'8001','formNumber':'NÄIDIS-TI-001','version':1,'status':'published','inspectorName':'Test Inspektor','inspectionDate':'2026-09-08','externalInspectionId':'EXT-TEST','inspectionType':'DEMO','companyName':'Näidisettevõte OÜ','companyRegCode':'TEST-8001','vehicleCount':3,'totalDriversCount':5,'controlsMatrix':[{'transportClass':'DEMO','analogRecorderDrivers':1,'analogRecorderWorkDays':4,'digitalRecorderDrivers':2,'digitalRecorderWorkDays':8,'smartRecorderDrivers':2,'smartRecorderWorkDays':6}],'prescriptionComposed':True,'punishedPersonIdCode':'TEST-CODE','punishedPersonFirstName':'Test','punishedPersonLastName':'Isik','proceedingReferenceNumber':'TEST-2026','enforcementDecision':'Näidisotsus','proceedingClosureBasis':'','violations':[{'level1ValueKey':'DEMO-1','level2ValueKey':'DEMO-2','level3ValueKey':'DEMO-3','quantity':1}]}}
payloads['good-repute']={'goodReputeForm':{'id':'9001','formNumber':'NÄIDIS-MV-001','version':1,'status':'published','personalCode':'TEST-CODE-9001','firstName':'Test','lastName':'Veokorraldaja','dateOfBirth':'1985-03-04','placeOfBirth':'Tallinn','certificateNumber':'CPC-TEST','certificateIssueDate':'2020-02-03','certificateCountryCode':'EE','fitnessStatus':'UNFIT','unfitFromDate':'2026-09-01','unfitUntilDate':'2027-09-01'},'labels':copy.deepcopy(base['labels'])}
tram=copy.deepcopy(c);tram.update(id='10001',formNumber='NÄIDIS-TRAM-001',version=1,status='published',transportType='Sõitjatevedu',transportNature='Tasuline',transportEmptyRun=False,driverNotApplicable=False,liiniNumber='1',liiniNimetus='Näidisliin',documentChecks=[{'documentName':'Juhiluba','violationCode':'DEMO','severityCode':'SI'}],otherDocuments=[{'documentName':'Veodokument','result':'Nõuetekohane'}],cabotageViolations=[],violations5612006=[{'violationCode':'SI901','severityCode':'SI','isDetected':True}],violations1652014=[],violations200215=[],violations5932008=[],violations20201057=[],resultType='warning',additionalMeasure='warning',proceedingType='LYHI',proceedingReferenceNumber='TEST-TRAM',notes='Sünteetilised näidisandmed.')
payloads['tram-card']={'tramCard':tram,'labels':copy.deepcopy(base['labels'])}
payloads['vehicle-technical']=dict(base,technicalForm={'id':'3001','compoundFormKey':1001,'subFormNumber':'NÄIDIS-T-001','version':1,'status':'published','resultType':'extraordinary_inspection','partsSummary':[{'partCode':'CAA_'+str(i),'status':'non_compliant' if i==1 else 'checked'} for i in range(10)],'partsDefects':[{'partCode':'CAA_1','defectCode':'CAA_1.1.11','severity':'OV'}],'notes':'SÜNTEETILISED ANDMED. Näidisrike PDF-kujunduse kontrollimiseks.'})
payloads['trailer-technical']=copy.deepcopy(payloads['vehicle-technical']);payloads['trailer-technical']['technicalForm']['trailerRegNr']='456DEF'
payloads['transport-interruption']=dict(base,transportInterruptionForm={'id':'4001','compoundFormKey':1001,'subFormNumber':'NÄIDIS-KV-001','version':1,'status':'published','headerText':'NÄIDISASUTUS · väljamõeldud andmed','residenceCountry':'EE','residenceCity':'Tallinn','residenceAddressLine':'Näidise tee 2','interruptionReason':'SÜNTEETILISED ANDMED. Puuduv veodokument, näidis otsuse kujunduse kontrollimiseks.','legalBases':['DEMO_ALUS'],'terminationCondition':'Kuni näidises kirjeldatud puuduse kõrvaldamiseni.','personApplications':'Näidistaotlus puudub.'},printOptions={'interruptionDate':'2026-09-09','interruptionTime':'10:40'})
payloads['transport-interruption']['labels']=copy.deepcopy(base['labels']);payloads['transport-interruption']['labels']['legalBases']={'DEMO_ALUS':'Näidis — õiguslik alus kinnitatakse tegelike andmete põhjal'}
payloads['drive-rest-form']=dict(base,driveRestForm={'id':'5001','compoundFormKey':1001,'subFormNumber':'NÄIDIS-SP-001','version':1,'status':'published','transportType':'Veosevedu','transportNature':'Tasuline','transportClasses':[{'classCode':'DEMO','className':'Näidisvedu'}],'documentChecks':[{'documentCode':'JUHILUBA','documentName':'Juhiluba','violationCode':'NÄIDIS','severityCode':'SI'}],'otherDocuments':[{'documentCode':'VEOSE_DOKUMENDID','documentName':'Veodokument','result':'NOUETEKOHANE','notes':''}],'spApplicability':'RAKENDATAKSE','tachographTypeCode':'DIGITAL','checkedDaysCount':'56','workDaysCount':'40','otherActivityDaysCount':'16','violations5612006':[{'violationCode':'SI901','severityCode':'SI','isDetected':'true'}],'massDimensionMeasurements':[{'measurementType':'Mass (kg)','actualValue':'18000','allowedValue':'18000','excessValue':'0','axleNumber':''}],'resultType':'warning','notes':'SÜNTEETILISED NÄIDISANDMED — ei kajasta tegelikku kontrolli.'})
payloads['rsi']={'rsiMessage':{'id':'6001','businessCaseId':'EE-RSI-NÄIDIS','rsiFrom':'EE','rsiTo':'FI','originatingAuthority':'KLIM','vehicleCategory':'N3','vehicleRegistrationNumber':'ABC123','vehicleRegistrationCountry':'FI','vehicleIdentificationNumber':'TESTVIN123','odometerReading':123456,'driverFirstName':'TEST','driverFamilyName':'DRIVER','driverLicenceNumber':'TEST123','driverLicenceCountry':'FI','inspectionIdentifier':'th-2026-000453/1','inspectionLocation':'Tallinn','inspectionDatetime':'2026-09-10T12:30:00','inspectionAuthorityOrName':'Politsei- ja Piirivalveamet','inspectionPassed':False,'ptiRequested':True,'vehicleProhibitionOrRestriction':False,'checkedItems':[{'partCode':'CAA_1','status':'non_compliant','defects':[{'defectCode':'CAA_1.1.1','severity':'OV'}]},{'partCode':'CAA_10','status':'checked','defects':[]},{'partCode':'CAA_20','status':'checked','defects':[]}]}}
for template,payload in payloads.items():
 folder=ROOT/'examples'/template;folder.mkdir(exist_ok=True)
 (folder/'filled.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2))
 for blank,name in [(True,'blank'),(False,'filled')]:
  html,warnings=render_html(payload,blank,template);pdf,_=render_pdf(payload,blank,template)
  (folder/(name+'.html')).write_text(html);(folder/(name+'.pdf')).write_bytes(pdf)
  print(template,name,len(pdf),warnings)
