FROM turnerrainer/ruuter@sha256:cc79c5821c59cb3e317a18977c58f2225a1c709e1ab9ddfbff2165051272e81e
RUN rm -rf /app/DSL/samples
COPY DSL/Ruuter/ljvis /app/DSL/ljvis
COPY constants.ini /app/constants.ini
COPY ruuter.yaml /app/ruuter.yaml
