FROM turnerrainer/ruuter:0.9.15-rc@sha256:f6f40aec9f5f6e1f8d580bddceaadc933558e788e92aa923ba77d1a0fba4c0cb
RUN rm -rf /app/DSL/samples
COPY DSL/Ruuter/ljvis /app/DSL/ljvis
COPY constants.ini /app/constants.ini
COPY ruuter.yaml /app/ruuter.yaml
